/* ==========================================================================
   万象矿工 Omni Miner — Localization file
   10 languages: zh, zh-TW, en, de, fr, ru, ja, pt-BR, es, ko
   Loaded before the main <script> in index.html — exposes:
     - window.I18N              UI text strings, keyed by language code
     - window.TERRAIN_NAME_I18N display names for terrains, keyed by the
                                 original (Chinese) terrain name used as the
                                 internal data id
   ========================================================================== */
const I18N = {
  zh: {
    title:'万象矿工', subtitle:'OMNI MINER', newgame:'开始游戏', continue_:'继续游戏', lang:'🌐 语言选择',
    tab_map:'地图', tab_shop:'商店', tab_warehouse:'仓库', tab_dex:'图鉴', exit:'回到主页',
    map_title:'地形选择', map_desc:'挑选一处地形入场挖矿。解锁新地形需要累计发现足够多的矿物种类。',
    enter:'进入挖矿', free:'免费', locked_need:'累计发现矿物 {n}/{t} 种解锁', need_gear:'需要装备：',
    not_enough_gold:'金币不足',
    shop_title:'装备商店', shop_desc:'装备一次性永久购买；升级类可重复购买、效果叠加。',
    owned:'已拥有', buy:'购买', max_lv:'已满级',
    wh_title:'仓库', wh_desc:'挖到的矿石会先放进仓库，来这里手动卖出换金币。锁定的矿石不会被卖出。', sell_all:'出售全部', sell_one:'出售1个', wh_empty:'仓库空空如也，去挖矿吧！',
    total_value:'仓库库存价值',
    dex_title:'矿物图鉴', dex_desc:'记录你发现过的所有矿物。', dex_progress:'已发现', dex_other:'其他',
    all:'全部', industrial:'工业矿物', gem:'常见宝石矿物', crystal:'珍稀晶体矿物', fossil:'化石',
    unknown:'？？？未发现',
    haul_title:'本次收获', confirm:'确认入库，返回地图', total_earn:'总收益', remain:'剩余矿物', leave:'结束挖掘',
    hint:'点击画面或按【空格】发射钩爪',
    dex_close:'关闭',
    price:'售价', formula:'化学式', category:'分类', rarity:'稀有度', note:'备注',
    r_common:'普通', r_uncommon:'少见', r_rare:'稀有', r_epic:'史诗', r_legend:'传说',
    equip_winch:{n:'强化绞盘', d:'钩爪伸缩速度 +25%，挖矿效率更高。'},
    equip_light:{n:'轻量化钩爪', d:'所有矿物的拖拽重量 -20%，收绳更快。'},
    equip_luck:{n:'幸运探测仪', d:'史诗、传说级矿物的出现概率提升为原来的 1.5 倍。'},
    equip_dive:{n:'潜水装备', d:'解锁地形【海底/海岸礁石】的必备装备。'},
    equip_cold:{n:'防寒装备', d:'解锁地形【极地/雪原冰川】的必备装备。'},
    equip_heat:{n:'耐热装备', d:'解锁地形【火山/熔岩区】的必备装备。'},
    shop_time_n:'延长开采时间', shop_time_d:'每次购买，单局挖矿时间 +5 秒，可重复购买。',
    time_cur:'当前单局时长',
    shop_det_n:'探矿仪升级', shop_det_d:'每次购买，单局矿物数量 +1 个，最多 20 个。',
    det_cur:'当前单局矿物数',
    shop_suit_n:'防护服', shop_suit_d:'一件可保护采集 10 次有毒矿物（辰砂/铀矿/石棉），用完即销毁，可多买堆叠。',
    suit_cur:'当前防护次数',
    hookslot_title:'多爪系统', hookslot_desc:'升级同时发射的钩爪数量，最多 3 只。',
    hookslot_cur:'当前钩爪数量', hookslot_buy:'升级钩爪数量',
    claw_title:'钩爪强化（每只钩爪独立升级）',
    claw_n:'{n}号爪', claw_locked:'尚未解锁',
    pierce_n:'穿透爪', pierce_d:'一次贯穿沿途所有矿物',
    reflect_n:'反射爪', reflect_d:'触底扑空后弹射一次再试',
    buy_short:'升级',
    faint_title:'采矿中断', faint_msg:'接触有毒矿物，你已晕倒。请去商店购买防护用品。', faint_btn:'前往商店',
    items_suffix:' 件矿物', each_suffix:'/个', unknown_short:'？？？',
    on_state:'开', off_state:'关', testmode_label:'测试模式：', lang_menu_title:'选择语言',
  },
  'zh-TW': {
    title:'萬象礦工', subtitle:'OMNI MINER', newgame:'開始遊戲', continue_:'繼續遊戲', lang:'🌐 語言選擇',
    tab_map:'地圖', tab_shop:'商店', tab_warehouse:'倉庫', tab_dex:'圖鑑', exit:'回到主頁',
    map_title:'地形選擇', map_desc:'挑選一處地形入場挖礦。解鎖新地形需要累計發現足夠多的礦物種類。',
    enter:'進入挖礦', free:'免費', locked_need:'累計發現礦物 {n}/{t} 種解鎖', need_gear:'需要裝備：',
    not_enough_gold:'金幣不足',
    shop_title:'裝備商店', shop_desc:'裝備一次性永久購買；升級類可重複購買、效果疊加。',
    owned:'已擁有', buy:'購買', max_lv:'已滿級',
    wh_title:'倉庫', wh_desc:'挖到的礦石會先放進倉庫，來這裡手動賣出換金幣。鎖定的礦石不會被賣出。', sell_all:'出售全部', sell_one:'出售1個', wh_empty:'倉庫空空如也，去挖礦吧！',
    total_value:'倉庫庫存價值',
    dex_title:'礦物圖鑑', dex_desc:'記錄你發現過的所有礦物。', dex_progress:'已發現', dex_other:'其他',
    all:'全部', industrial:'工業礦物', gem:'常見寶石礦物', crystal:'珍稀晶體礦物', fossil:'化石',
    unknown:'？？？未發現',
    haul_title:'本次收穫', confirm:'確認入庫，返回地圖', total_earn:'總收益', remain:'剩餘礦物', leave:'結束挖掘',
    hint:'點擊畫面或按【空格】發射鉤爪',
    dex_close:'關閉',
    price:'售價', formula:'化學式', category:'分類', rarity:'稀有度', note:'備註',
    r_common:'普通', r_uncommon:'少見', r_rare:'稀有', r_epic:'史詩', r_legend:'傳說',
    equip_winch:{n:'強化絞盤', d:'鉤爪伸縮速度 +25%，挖礦效率更高。'},
    equip_light:{n:'輕量化鉤爪', d:'所有礦物的拖曳重量 -20%，收繩更快。'},
    equip_luck:{n:'幸運探測儀', d:'史詩、傳說級礦物的出現機率提升為原來的 1.5 倍。'},
    equip_dive:{n:'潛水裝備', d:'解鎖地形【海底/海岸礁石】的必備裝備。'},
    equip_cold:{n:'防寒裝備', d:'解鎖地形【極地/雪原冰川】的必備裝備。'},
    equip_heat:{n:'耐熱裝備', d:'解鎖地形【火山/熔岩區】的必備裝備。'},
    shop_time_n:'延長開採時間', shop_time_d:'每次購買，單局挖礦時間 +5 秒，可重複購買。',
    time_cur:'當前單局時長',
    shop_det_n:'探礦儀升級', shop_det_d:'每次購買，單局礦物數量 +1 個，最多 20 個。',
    det_cur:'當前單局礦物數',
    shop_suit_n:'防護服', shop_suit_d:'一件可保護採集 10 次有毒礦物（辰砂/鈾礦/石棉），用完即銷毀，可多買疊加。',
    suit_cur:'當前防護次數',
    hookslot_title:'多爪系統', hookslot_desc:'升級同時發射的鉤爪數量，最多 3 隻。',
    hookslot_cur:'當前鉤爪數量', hookslot_buy:'升級鉤爪數量',
    claw_title:'鉤爪強化（每隻鉤爪獨立升級）',
    claw_n:'{n}號爪', claw_locked:'尚未解鎖',
    pierce_n:'穿透爪', pierce_d:'一次貫穿沿途所有礦物',
    reflect_n:'反射爪', reflect_d:'觸底撲空後彈射一次再試',
    buy_short:'升級',
    faint_title:'採礦中斷', faint_msg:'接觸有毒礦物，你已暈倒。請去商店購買防護用品。', faint_btn:'前往商店',
    items_suffix:' 件礦物', each_suffix:'/個', unknown_short:'？？？',
    on_state:'開', off_state:'關', testmode_label:'測試模式：', lang_menu_title:'選擇語言',
  },
  en: {
    title:'Omni Miner', subtitle:'万象矿工', newgame:'New Game', continue_:'Continue', lang:'🌐 Language',
    tab_map:'Map', tab_shop:'Shop', tab_warehouse:'Warehouse', tab_dex:'Dex', exit:'Home',
    map_title:'Choose a Site', map_desc:'Pick a terrain to enter and mine. Unlock new terrains by discovering enough mineral species overall.',
    enter:'Enter Mine', free:'Free', locked_need:'Discover {n}/{t} species to unlock', need_gear:'Requires gear: ',
    not_enough_gold:'Not enough gold',
    shop_title:'Equipment Shop', shop_desc:'Gear is a one-time permanent purchase; upgrades are repeatable and stack.',
    owned:'Owned', buy:'Buy', max_lv:'Maxed',
    wh_title:'Warehouse', wh_desc:'Ore you dig up goes into the warehouse first — sell it here for gold. Locked ore cannot be sold.', sell_all:'Sell All', sell_one:'Sell 1', wh_empty:'Warehouse is empty. Go mine something!',
    total_value:'Warehouse stock value',
    dex_title:'Mineral Dex', dex_desc:'Everything you have ever discovered.', dex_progress:'Discovered', dex_other:'Other',
    all:'All', industrial:'Industrial', gem:'Common Gems', crystal:'Rare Crystals', fossil:'Fossils',
    unknown:'????? Undiscovered',
    haul_title:'Haul This Run', confirm:'Bank it & return to map', total_earn:'Total Earnings', remain:'Left', leave:'Leave Mine',
    hint:'Click or press SPACE to swing the hook',
    dex_close:'Close',
    price:'Price', formula:'Formula', category:'Category', rarity:'Rarity', note:'Note',
    r_common:'Common', r_uncommon:'Uncommon', r_rare:'Rare', r_epic:'Epic', r_legend:'Legendary',
    equip_winch:{n:'Reinforced Winch', d:'+25% hook extend/retract speed.'},
    equip_light:{n:'Light Claw', d:'-20% drag weight on all minerals — reel in faster.'},
    equip_luck:{n:'Lucky Detector', d:'Epic and legendary mineral odds ×1.5.'},
    equip_dive:{n:'Diving Gear', d:'Required to unlock the Seabed/Reef terrain.'},
    equip_cold:{n:'Cold Gear', d:'Required to unlock the Polar Icefields terrain.'},
    equip_heat:{n:'Heat Suit', d:'Required to unlock the Volcanic Zone terrain.'},
    shop_time_n:'Extend Dig Time', shop_time_d:'Each purchase adds +5s to every mining run. Repeatable.',
    time_cur:'Current run length',
    shop_det_n:'Detector Upgrade', shop_det_d:'Each purchase gives +1 mineral per run, up to 20.',
    det_cur:'Current minerals/run',
    shop_suit_n:'Protective Suit', shop_suit_d:'Each suit protects 10 hazardous catches (cinnabar/uranium/asbestos), then is destroyed. Stackable.',
    suit_cur:'Charges remaining',
    hookslot_title:'Multi-Claw System', hookslot_desc:'Upgrade how many claws fire at once, up to 3.',
    hookslot_cur:'Active claws', hookslot_buy:'Upgrade claw count',
    claw_title:'Claw Enhancements (each claw upgrades independently)',
    claw_n:'Claw {n}', claw_locked:'Not unlocked',
    pierce_n:'Piercing Claw', pierce_d:'Grabs every mineral along its path in one throw',
    reflect_n:'Reflect Claw', reflect_d:'Bounces once and retries if it comes up empty',
    buy_short:'Upgrade',
    faint_title:'Mining Interrupted', faint_msg:'You touched a toxic mineral and passed out. Head to the shop for protective gear.', faint_btn:'Go to Shop',
    items_suffix:' items', each_suffix:'each', unknown_short:'???',
    on_state:'ON', off_state:'OFF', testmode_label:'Test Mode: ', lang_menu_title:'Select Language',
  },
  de: {
    title:'Omni Miner', subtitle:'万象矿工', newgame:'Neues Spiel', continue_:'Fortsetzen', lang:'🌐 Sprache',
    tab_map:'Karte', tab_shop:'Shop', tab_warehouse:'Lager', tab_dex:'Dex', exit:'Startseite',
    map_title:'Gebiet wählen', map_desc:'Wähle ein Gelände zum Schürfen. Neue Gelände werden freigeschaltet, sobald du genug Mineralarten insgesamt entdeckt hast.',
    enter:'Mine betreten', free:'Kostenlos', locked_need:'{n}/{t} Arten entdecken zum Freischalten', need_gear:'Benötigt Ausrüstung: ',
    not_enough_gold:'Nicht genug Gold',
    shop_title:'Ausrüstungsshop', shop_desc:'Ausrüstung ist ein einmaliger, dauerhafter Kauf; Upgrades sind wiederholbar und stapelbar.',
    owned:'Im Besitz', buy:'Kaufen', max_lv:'Maximal',
    wh_title:'Lager', wh_desc:'Geförderte Erze landen zuerst im Lager – verkaufe sie hier für Gold. Gesperrte Erze können nicht verkauft werden.', sell_all:'Alle verkaufen', sell_one:'1 verkaufen', wh_empty:'Das Lager ist leer. Geh schürfen!',
    total_value:'Lagerwert',
    dex_title:'Mineral-Dex', dex_desc:'Alles, was du bisher entdeckt hast.', dex_progress:'Entdeckt', dex_other:'Sonstiges',
    all:'Alle', industrial:'Industriemineralien', gem:'Verbreitete Edelsteine', crystal:'Seltene Kristalle', fossil:'Fossilien',
    unknown:'????? Unentdeckt',
    haul_title:'Ausbeute dieser Runde', confirm:'Einlagern & zur Karte zurückkehren', total_earn:'Gesamteinnahmen', remain:'Übrig', leave:'Mine verlassen',
    hint:'Klicke oder drücke LEERTASTE, um den Haken zu schwingen',
    dex_close:'Schließen',
    price:'Preis', formula:'Formel', category:'Kategorie', rarity:'Seltenheit', note:'Notiz',
    r_common:'Gewöhnlich', r_uncommon:'Ungewöhnlich', r_rare:'Selten', r_epic:'Episch', r_legend:'Legendär',
    equip_winch:{n:'Verstärkte Winde', d:'+25% Geschwindigkeit beim Aus-/Einfahren des Hakens.'},
    equip_light:{n:'Leichter Greifer', d:'-20% Zuggewicht bei allen Mineralien – schnelleres Einholen.'},
    equip_luck:{n:'Glücksdetektor', d:'Chance auf epische und legendäre Mineralien ×1,5.'},
    equip_dive:{n:'Tauchausrüstung', d:'Erforderlich, um das Gelände Meeresboden/Riff freizuschalten.'},
    equip_cold:{n:'Kälteschutz', d:'Erforderlich, um das Gelände Polare Eisfelder freizuschalten.'},
    equip_heat:{n:'Hitzeschutzanzug', d:'Erforderlich, um das Gelände Vulkanzone freizuschalten.'},
    shop_time_n:'Grabzeit verlängern', shop_time_d:'Jeder Kauf verlängert jede Mining-Runde um +5 Sek. Wiederholbar.',
    time_cur:'Aktuelle Rundenlänge',
    shop_det_n:'Detektor-Upgrade', shop_det_d:'Jeder Kauf gibt +1 Mineral pro Runde, bis zu 20.',
    det_cur:'Aktuelle Mineralien/Runde',
    shop_suit_n:'Schutzanzug', shop_suit_d:'Jeder Anzug schützt bei 10 gefährlichen Fängen (Zinnober/Uran/Asbest) und wird danach zerstört. Stapelbar.',
    suit_cur:'Verbleibende Ladungen',
    hookslot_title:'Mehrfach-Greifer-System', hookslot_desc:'Erhöhe die Anzahl gleichzeitig abgefeuerter Greifer, bis zu 3.',
    hookslot_cur:'Aktive Greifer', hookslot_buy:'Greiferanzahl aufwerten',
    claw_title:'Greifer-Verbesserungen (jeder Greifer wird unabhängig aufgewertet)',
    claw_n:'Greifer {n}', claw_locked:'Nicht freigeschaltet',
    pierce_n:'Durchdringungsgreifer', pierce_d:'Erfasst mit einem Wurf alle Mineralien entlang des Wegs',
    reflect_n:'Reflexgreifer', reflect_d:'Prallt bei leerem Fang einmal ab und versucht es erneut',
    buy_short:'Aufwerten',
    faint_title:'Abbau unterbrochen', faint_msg:'Du hast ein giftiges Mineral berührt und bist ohnmächtig geworden. Geh zum Shop und kaufe Schutzausrüstung.', faint_btn:'Zum Shop',
    items_suffix:' Objekte', each_suffix:'je Stück', unknown_short:'???',
    on_state:'AN', off_state:'AUS', testmode_label:'Testmodus: ', lang_menu_title:'Sprache wählen',
  },
  fr: {
    title:'Omni Miner', subtitle:'万象矿工', newgame:'Nouvelle partie', continue_:'Continuer', lang:'🌐 Langue',
    tab_map:'Carte', tab_shop:'Boutique', tab_warehouse:'Entrepôt', tab_dex:'Dex', exit:'Accueil',
    map_title:'Choisir un site', map_desc:"Choisissez un terrain pour miner. Débloquez de nouveaux terrains en découvrant suffisamment d'espèces de minéraux au total.",
    enter:'Entrer dans la mine', free:'Gratuit', locked_need:'Découvrez {n}/{t} espèces pour débloquer', need_gear:'Équipement requis : ',
    not_enough_gold:'Or insuffisant',
    shop_title:"Boutique d'équipement", shop_desc:"L'équipement est un achat permanent unique ; les améliorations sont répétables et cumulables.",
    owned:'Possédé', buy:'Acheter', max_lv:'Maximum',
    wh_title:'Entrepôt', wh_desc:"Le minerai extrait va d'abord dans l'entrepôt — vendez-le ici contre de l'or. Le minerai verrouillé ne peut pas être vendu.", sell_all:'Tout vendre', sell_one:'Vendre 1', wh_empty:'Entrepôt vide. Allez miner !',
    total_value:'Valeur du stock',
    dex_title:'Dex des minéraux', dex_desc:"Tout ce que vous avez découvert jusqu'à présent.", dex_progress:'Découverts', dex_other:'Autres',
    all:'Tous', industrial:'Minéraux industriels', gem:'Pierres précieuses courantes', crystal:'Cristaux rares', fossil:'Fossiles',
    unknown:'????? Non découvert',
    haul_title:'Butin de cette partie', confirm:'Stocker et retourner à la carte', total_earn:'Gains totaux', remain:'Restant', leave:'Quitter la mine',
    hint:'Cliquez ou appuyez sur ESPACE pour lancer le grappin',
    dex_close:'Fermer',
    price:'Prix', formula:'Formule', category:'Catégorie', rarity:'Rareté', note:'Remarque',
    r_common:'Commun', r_uncommon:'Peu commun', r_rare:'Rare', r_epic:'Épique', r_legend:'Légendaire',
    equip_winch:{n:'Treuil renforcé', d:"+25% de vitesse d'extension/rétraction du grappin."},
    equip_light:{n:'Grappin léger', d:'-20% de poids de traction sur tous les minéraux — remontée plus rapide.'},
    equip_luck:{n:'Détecteur chanceux', d:'Probabilité de minéraux épiques et légendaires ×1,5.'},
    equip_dive:{n:'Équipement de plongée', d:'Requis pour débloquer le terrain Fond marin/Récif.'},
    equip_cold:{n:'Équipement grand froid', d:'Requis pour débloquer le terrain Glacier polaire.'},
    equip_heat:{n:'Combinaison thermique', d:'Requis pour débloquer le terrain Zone volcanique.'},
    shop_time_n:'Prolonger le temps de forage', shop_time_d:'Chaque achat ajoute +5 s à chaque partie de minage. Répétable.',
    time_cur:'Durée actuelle de la partie',
    shop_det_n:'Amélioration du détecteur', shop_det_d:"Chaque achat donne +1 minéral par partie, jusqu'à 20.",
    det_cur:'Minéraux actuels/partie',
    shop_suit_n:'Combinaison de protection', shop_suit_d:'Chaque combinaison protège 10 prises dangereuses (cinabre/uranium/amiante), puis est détruite. Cumulable.',
    suit_cur:'Charges restantes',
    hookslot_title:'Système multi-grappins', hookslot_desc:'Augmentez le nombre de grappins lancés simultanément, jusqu\'à 3.',
    hookslot_cur:'Grappins actifs', hookslot_buy:'Améliorer le nombre de grappins',
    claw_title:"Améliorations des grappins (chaque grappin s'améliore indépendamment)",
    claw_n:'Grappin {n}', claw_locked:'Non débloqué',
    pierce_n:'Grappin perforant', pierce_d:'Attrape tous les minéraux sur son passage en un seul lancer',
    reflect_n:'Grappin réflecteur', reflect_d:'Rebondit une fois et réessaie si vide',
    buy_short:'Améliorer',
    faint_title:'Extraction interrompue', faint_msg:"Vous avez touché un minéral toxique et vous êtes évanoui. Rendez-vous à la boutique pour acheter de l'équipement de protection.", faint_btn:'Aller à la boutique',
    items_suffix:' objets', each_suffix:'chacun', unknown_short:'???',
    on_state:'ON', off_state:'OFF', testmode_label:'Mode test : ', lang_menu_title:'Choisir la langue',
  },
  ru: {
    title:'Omni Miner', subtitle:'万象矿工', newgame:'Новая игра', continue_:'Продолжить', lang:'🌐 Язык',
    tab_map:'Карта', tab_shop:'Магазин', tab_warehouse:'Склад', tab_dex:'Дех', exit:'На главную',
    map_title:'Выбор участка', map_desc:'Выберите местность для добычи. Новые местности открываются по мере обнаружения достаточного числа видов минералов.',
    enter:'Войти в шахту', free:'Бесплатно', locked_need:'Откройте {n}/{t} видов для разблокировки', need_gear:'Необходимо снаряжение: ',
    not_enough_gold:'Недостаточно золота',
    shop_title:'Магазин снаряжения', shop_desc:'Снаряжение покупается один раз навсегда; улучшения можно покупать многократно, эффекты суммируются.',
    owned:'Есть', buy:'Купить', max_lv:'Максимум',
    wh_title:'Склад', wh_desc:'Добытая руда сначала попадает на склад — продавайте её здесь за золото. Заблокированную руду продать нельзя.', sell_all:'Продать всё', sell_one:'Продать 1', wh_empty:'Склад пуст. Идите добывать!',
    total_value:'Стоимость запасов склада',
    dex_title:'Справочник минералов', dex_desc:'Всё, что вы когда-либо находили.', dex_progress:'Найдено', dex_other:'Прочее',
    all:'Все', industrial:'Промышленные минералы', gem:'Обычные драгоценные камни', crystal:'Редкие кристаллы', fossil:'Окаменелости',
    unknown:'????? Не найдено',
    haul_title:'Добыча за этот заход', confirm:'Сохранить и вернуться на карту', total_earn:'Общий доход', remain:'Осталось', leave:'Покинуть шахту',
    hint:'Нажмите или используйте ПРОБЕЛ, чтобы забросить крюк',
    dex_close:'Закрыть',
    price:'Цена', formula:'Формула', category:'Категория', rarity:'Редкость', note:'Заметка',
    r_common:'Обычный', r_uncommon:'Необычный', r_rare:'Редкий', r_epic:'Эпический', r_legend:'Легендарный',
    equip_winch:{n:'Усиленная лебёдка', d:'Скорость выдвижения/втягивания крюка +25%.'},
    equip_light:{n:'Лёгкий захват', d:'Вес перетаскивания всех минералов −20% — быстрее сматывание.'},
    equip_luck:{n:'Счастливый детектор', d:'Шанс на эпические и легендарные минералы ×1,5.'},
    equip_dive:{n:'Водолазное снаряжение', d:'Необходимо для открытия местности «Морское дно/риф».'},
    equip_cold:{n:'Снаряжение от холода', d:'Необходимо для открытия местности «Полярные ледники».'},
    equip_heat:{n:'Термокостюм', d:'Необходимо для открытия местности «Вулканическая зона».'},
    shop_time_n:'Увеличить время добычи', shop_time_d:'Каждая покупка добавляет +5 сек к каждому заходу. Можно покупать многократно.',
    time_cur:'Текущая длительность захода',
    shop_det_n:'Улучшение детектора', shop_det_d:'Каждая покупка даёт +1 минерал за заход, максимум 20.',
    det_cur:'Текущее число минералов/заход',
    shop_suit_n:'Защитный костюм', shop_suit_d:'Один костюм защищает от 10 опасных находок (киноварь/уран/асбест), затем уничтожается. Можно накапливать.',
    suit_cur:'Осталось зарядов',
    hookslot_title:'Система нескольких крюков', hookslot_desc:'Увеличьте число одновременно выстреливаемых крюков, максимум 3.',
    hookslot_cur:'Активных крюков', hookslot_buy:'Улучшить число крюков',
    claw_title:'Улучшения крюков (каждый крюк улучшается отдельно)',
    claw_n:'Крюк {n}', claw_locked:'Не разблокирован',
    pierce_n:'Пронзающий крюк', pierce_d:'Захватывает все минералы на пути за один бросок',
    reflect_n:'Отражающий крюк', reflect_d:'При промахе один раз отскакивает и пробует снова',
    buy_short:'Улучшить',
    faint_title:'Добыча прервана', faint_msg:'Вы коснулись токсичного минерала и потеряли сознание. Отправляйтесь в магазин за защитным снаряжением.', faint_btn:'В магазин',
    items_suffix:' предм.', each_suffix:'за шт.', unknown_short:'???',
    on_state:'ВКЛ', off_state:'ВЫКЛ', testmode_label:'Тестовый режим: ', lang_menu_title:'Выбор языка',
  },
  ja: {
    title:'オムニマイナー', subtitle:'万象矿工', newgame:'新しく始める', continue_:'続ける', lang:'🌐 言語',
    tab_map:'マップ', tab_shop:'ショップ', tab_warehouse:'倉庫', tab_dex:'図鑑', exit:'ホームへ',
    map_title:'採掘地を選ぶ', map_desc:'採掘する地形を選んでください。累計で十分な種類の鉱物を発見すると新しい地形が解放されます。',
    enter:'採掘へ', free:'無料', locked_need:'鉱物を{n}/{t}種発見で解放', need_gear:'必要装備：',
    not_enough_gold:'ゴールドが足りません',
    shop_title:'装備ショップ', shop_desc:'装備は一度きりの永久購入、アップグレードは繰り返し購入でき効果が重なります。',
    owned:'所持済み', buy:'購入', max_lv:'最大',
    wh_title:'倉庫', wh_desc:'採掘した鉱石はまず倉庫に入ります。ここで手動で売ってゴールドに換えましょう。ロックした鉱石は売却されません。', sell_all:'全部売却', sell_one:'1個売却', wh_empty:'倉庫は空っぽです。採掘に行きましょう！',
    total_value:'倉庫在庫の価値',
    dex_title:'鉱物図鑑', dex_desc:'これまでに発見したすべての鉱物。', dex_progress:'発見済み', dex_other:'その他',
    all:'すべて', industrial:'工業鉱物', gem:'一般宝石鉱物', crystal:'希少結晶鉱物', fossil:'化石',
    unknown:'？？？未発見',
    haul_title:'今回の収穫', confirm:'収納してマップへ戻る', total_earn:'合計収益', remain:'残り', leave:'採掘を終了',
    hint:'画面をクリックまたは【スペース】キーでフックを発射',
    dex_close:'閉じる',
    price:'売値', formula:'化学式', category:'分類', rarity:'レア度', note:'備考',
    r_common:'コモン', r_uncommon:'アンコモン', r_rare:'レア', r_epic:'エピック', r_legend:'レジェンド',
    equip_winch:{n:'強化ウインチ', d:'フックの伸縮速度が+25%になる。'},
    equip_light:{n:'軽量化フック', d:'すべての鉱物のドラッグ重量が-20%になり、巻き取りが速くなる。'},
    equip_luck:{n:'幸運探知機', d:'エピック・レジェンド級鉱物の出現確率が1.5倍になる。'},
    equip_dive:{n:'潜水装備', d:'地形「海底・沿岸の岩礁」の解放に必要。'},
    equip_cold:{n:'防寒装備', d:'地形「極地・雪原氷河」の解放に必要。'},
    equip_heat:{n:'耐熱装備', d:'地形「火山・溶岩地帯」の解放に必要。'},
    shop_time_n:'採掘時間延長', shop_time_d:'購入ごとに1回の採掘時間が+5秒。何度でも購入可能。',
    time_cur:'現在の1回の制限時間',
    shop_det_n:'探鉱機アップグレード', shop_det_d:'購入ごとに1回の鉱物数が+1個、最大20個まで。',
    det_cur:'現在の1回あたりの鉱物数',
    shop_suit_n:'防護服', shop_suit_d:'1着で有毒鉱物（辰砂／ウラン鉱／石綿）の採取を10回保護し、使い切ると消滅。複数所持可。',
    suit_cur:'現在の保護回数',
    hookslot_title:'マルチフックシステム', hookslot_desc:'同時に発射できるフックの数をアップグレード、最大3本。',
    hookslot_cur:'現在のフック数', hookslot_buy:'フック数をアップグレード',
    claw_title:'フック強化（各フックは個別にアップグレード）',
    claw_n:'{n}号フック', claw_locked:'未解放',
    pierce_n:'貫通フック', pierce_d:'一投で経路上のすべての鉱物を回収する',
    reflect_n:'反射フック', reflect_d:'空振り時に一度跳ね返って再挑戦する',
    buy_short:'アップグレード',
    faint_title:'採掘中断', faint_msg:'有毒鉱物に触れて気絶しました。ショップで防護装備を購入してください。', faint_btn:'ショップへ',
    items_suffix:'個の鉱物', each_suffix:'/個', unknown_short:'？？？',
    on_state:'オン', off_state:'オフ', testmode_label:'テストモード：', lang_menu_title:'言語を選択',
  },
  'pt-BR': {
    title:'Omni Miner', subtitle:'万象矿工', newgame:'Novo Jogo', continue_:'Continuar', lang:'🌐 Idioma',
    tab_map:'Mapa', tab_shop:'Loja', tab_warehouse:'Armazém', tab_dex:'Dex', exit:'Início',
    map_title:'Escolher Local', map_desc:'Escolha um terreno para minerar. Desbloqueie novos terrenos descobrindo espécies de minerais suficientes no total.',
    enter:'Entrar na Mina', free:'Grátis', locked_need:'Descubra {n}/{t} espécies para desbloquear', need_gear:'Equipamento necessário: ',
    not_enough_gold:'Ouro insuficiente',
    shop_title:'Loja de Equipamentos', shop_desc:'Equipamentos são uma compra única e permanente; upgrades são repetíveis e acumuláveis.',
    owned:'Possuído', buy:'Comprar', max_lv:'Máximo',
    wh_title:'Armazém', wh_desc:'O minério extraído vai primeiro para o armazém — venda-o aqui por ouro. Minério bloqueado não pode ser vendido.', sell_all:'Vender Tudo', sell_one:'Vender 1', wh_empty:'O armazém está vazio. Vá minerar algo!',
    total_value:'Valor do estoque do armazém',
    dex_title:'Dex de Minerais', dex_desc:'Tudo o que você já descobriu.', dex_progress:'Descobertos', dex_other:'Outros',
    all:'Todos', industrial:'Minerais Industriais', gem:'Gemas Comuns', crystal:'Cristais Raros', fossil:'Fósseis',
    unknown:'????? Não descoberto',
    haul_title:'Coleta desta Partida', confirm:'Guardar e voltar ao mapa', total_earn:'Ganhos Totais', remain:'Restante', leave:'Sair da Mina',
    hint:'Clique ou pressione ESPAÇO para lançar o gancho',
    dex_close:'Fechar',
    price:'Preço', formula:'Fórmula', category:'Categoria', rarity:'Raridade', note:'Nota',
    r_common:'Comum', r_uncommon:'Incomum', r_rare:'Raro', r_epic:'Épico', r_legend:'Lendário',
    equip_winch:{n:'Guincho Reforçado', d:'+25% de velocidade de extensão/retração do gancho.'},
    equip_light:{n:'Garra Leve', d:'-20% de peso de arrasto em todos os minerais — recolhe mais rápido.'},
    equip_luck:{n:'Detector da Sorte', d:'Chance de minerais épicos e lendários ×1,5.'},
    equip_dive:{n:'Equipamento de Mergulho', d:'Necessário para desbloquear o terreno Fundo do Mar/Recife.'},
    equip_cold:{n:'Equipamento contra Frio', d:'Necessário para desbloquear o terreno Geleira Polar.'},
    equip_heat:{n:'Traje Térmico', d:'Necessário para desbloquear o terreno Zona Vulcânica.'},
    shop_time_n:'Estender Tempo de Escavação', shop_time_d:'Cada compra adiciona +5s a cada partida de mineração. Repetível.',
    time_cur:'Duração atual da partida',
    shop_det_n:'Upgrade do Detector', shop_det_d:'Cada compra dá +1 mineral por partida, até 20.',
    det_cur:'Minerais atuais/partida',
    shop_suit_n:'Traje de Proteção', shop_suit_d:'Cada traje protege 10 capturas perigosas (cinábrio/urânio/amianto), depois é destruído. Acumulável.',
    suit_cur:'Cargas restantes',
    hookslot_title:'Sistema Multi-Garra', hookslot_desc:'Aumente quantas garras disparam ao mesmo tempo, até 3.',
    hookslot_cur:'Garras ativas', hookslot_buy:'Melhorar número de garras',
    claw_title:'Melhorias das Garras (cada garra é aprimorada independentemente)',
    claw_n:'Garra {n}', claw_locked:'Não desbloqueada',
    pierce_n:'Garra Perfurante', pierce_d:'Captura todos os minerais no caminho em um único lançamento',
    reflect_n:'Garra Reflexiva', reflect_d:'Quica uma vez e tenta de novo se voltar vazia',
    buy_short:'Melhorar',
    faint_title:'Mineração Interrompida', faint_msg:'Você tocou em um mineral tóxico e desmaiou. Vá até a loja comprar equipamento de proteção.', faint_btn:'Ir para a Loja',
    items_suffix:' itens', each_suffix:'cada', unknown_short:'???',
    on_state:'LIGADO', off_state:'DESLIGADO', testmode_label:'Modo de teste: ', lang_menu_title:'Selecionar idioma',
  },
  es: {
    title:'Omni Miner', subtitle:'万象矿工', newgame:'Nueva Partida', continue_:'Continuar', lang:'🌐 Idioma',
    tab_map:'Mapa', tab_shop:'Tienda', tab_warehouse:'Almacén', tab_dex:'Dex', exit:'Inicio',
    map_title:'Elegir Terreno', map_desc:'Elige un terreno para entrar y minar. Desbloquea nuevos terrenos descubriendo suficientes especies de minerales en total.',
    enter:'Entrar a la Mina', free:'Gratis', locked_need:'Descubre {n}/{t} especies para desbloquear', need_gear:'Equipo requerido: ',
    not_enough_gold:'Oro insuficiente',
    shop_title:'Tienda de Equipo', shop_desc:'El equipo es una compra única y permanente; las mejoras son repetibles y acumulables.',
    owned:'Adquirido', buy:'Comprar', max_lv:'Al máximo',
    wh_title:'Almacén', wh_desc:'El mineral que extraes va primero al almacén; véndelo aquí por oro. El mineral bloqueado no se puede vender.', sell_all:'Vender Todo', sell_one:'Vender 1', wh_empty:'El almacén está vacío. ¡Ve a minar algo!',
    total_value:'Valor del inventario del almacén',
    dex_title:'Dex de Minerales', dex_desc:'Todo lo que has descubierto hasta ahora.', dex_progress:'Descubiertos', dex_other:'Otros',
    all:'Todos', industrial:'Minerales Industriales', gem:'Gemas Comunes', crystal:'Cristales Raros', fossil:'Fósiles',
    unknown:'????? Sin descubrir',
    haul_title:'Botín de esta Partida', confirm:'Guardar y volver al mapa', total_earn:'Ganancias Totales', remain:'Restante', leave:'Salir de la Mina',
    hint:'Haz clic o presiona ESPACIO para lanzar el gancho',
    dex_close:'Cerrar',
    price:'Precio', formula:'Fórmula', category:'Categoría', rarity:'Rareza', note:'Nota',
    r_common:'Común', r_uncommon:'Poco común', r_rare:'Raro', r_epic:'Épico', r_legend:'Legendario',
    equip_winch:{n:'Torno Reforzado', d:'+25% de velocidad al extender/retraer el gancho.'},
    equip_light:{n:'Garra Liviana', d:'-20% de peso de arrastre en todos los minerales; recoges más rápido.'},
    equip_luck:{n:'Detector de la Suerte', d:'Probabilidad de minerales épicos y legendarios ×1.5.'},
    equip_dive:{n:'Equipo de Buceo', d:'Necesario para desbloquear el terreno Fondo Marino/Arrecife.'},
    equip_cold:{n:'Equipo Anticongelante', d:'Necesario para desbloquear el terreno Glaciar Polar.'},
    equip_heat:{n:'Traje Térmico', d:'Necesario para desbloquear el terreno Zona Volcánica.'},
    shop_time_n:'Extender Tiempo de Excavación', shop_time_d:'Cada compra añade +5s a cada partida de minería. Repetible.',
    time_cur:'Duración actual de la partida',
    shop_det_n:'Mejora del Detector', shop_det_d:'Cada compra otorga +1 mineral por partida, hasta 20.',
    det_cur:'Minerales actuales/partida',
    shop_suit_n:'Traje Protector', shop_suit_d:'Cada traje protege 10 capturas peligrosas (cinabrio/uranio/asbesto), luego se destruye. Acumulable.',
    suit_cur:'Cargas restantes',
    hookslot_title:'Sistema Multi-Garra', hookslot_desc:'Aumenta cuántas garras se disparan a la vez, hasta 3.',
    hookslot_cur:'Garras activas', hookslot_buy:'Mejorar cantidad de garras',
    claw_title:'Mejoras de Garra (cada garra mejora de forma independiente)',
    claw_n:'Garra {n}', claw_locked:'No desbloqueada',
    pierce_n:'Garra Perforante', pierce_d:'Captura todos los minerales en su trayectoria en un solo lanzamiento',
    reflect_n:'Garra Reflectante', reflect_d:'Rebota una vez y vuelve a intentarlo si vuelve vacía',
    buy_short:'Mejorar',
    faint_title:'Minería Interrumpida', faint_msg:'Tocaste un mineral tóxico y te desmayaste. Ve a la tienda a comprar equipo de protección.', faint_btn:'Ir a la Tienda',
    items_suffix:' objetos', each_suffix:'c/u', unknown_short:'???',
    on_state:'ACTIVADO', off_state:'DESACTIVADO', testmode_label:'Modo de prueba: ', lang_menu_title:'Seleccionar idioma',
  },
  ko: {
    title:'오므니 마이너', subtitle:'万象矿工', newgame:'새 게임', continue_:'이어하기', lang:'🌐 언어',
    tab_map:'지도', tab_shop:'상점', tab_warehouse:'창고', tab_dex:'도감', exit:'홈으로',
    map_title:'지형 선택', map_desc:'채굴할 지형을 선택하세요. 누적으로 충분한 종류의 광물을 발견하면 새로운 지형이 해금됩니다.',
    enter:'채굴 입장', free:'무료', locked_need:'광물 {n}/{t}종 발견 시 해금', need_gear:'필요 장비: ',
    not_enough_gold:'골드가 부족합니다',
    shop_title:'장비 상점', shop_desc:'장비는 1회 영구 구매이며, 업그레이드는 반복 구매가 가능하고 효과가 누적됩니다.',
    owned:'보유 중', buy:'구매', max_lv:'최대 레벨',
    wh_title:'창고', wh_desc:'채굴한 광석은 먼저 창고에 들어갑니다. 여기서 직접 팔아 골드로 바꾸세요. 잠긴 광석은 판매되지 않습니다.', sell_all:'전부 판매', sell_one:'1개 판매', wh_empty:'창고가 비어 있습니다. 채굴하러 가세요!',
    total_value:'창고 재고 가치',
    dex_title:'광물 도감', dex_desc:'지금까지 발견한 모든 광물입니다.', dex_progress:'발견됨', dex_other:'기타',
    all:'전체', industrial:'산업 광물', gem:'일반 보석 광물', crystal:'희귀 결정 광물', fossil:'화석',
    unknown:'????? 미발견',
    haul_title:'이번 채굴 수확', confirm:'입고하고 지도로 돌아가기', total_earn:'총 수익', remain:'남은 광물', leave:'채굴 종료',
    hint:'화면을 클릭하거나 【스페이스】를 눌러 고리를 발사하세요',
    dex_close:'닫기',
    price:'판매가', formula:'화학식', category:'분류', rarity:'희귀도', note:'비고',
    r_common:'일반', r_uncommon:'희소', r_rare:'희귀', r_epic:'에픽', r_legend:'전설',
    equip_winch:{n:'강화 윈치', d:'고리 신축 속도 +25%.'},
    equip_light:{n:'경량 클로', d:'모든 광물의 견인 무게 -20%, 회수 속도 향상.'},
    equip_luck:{n:'행운 탐지기', d:'에픽·전설 등급 광물 출현 확률이 1.5배로 증가.'},
    equip_dive:{n:'잠수 장비', d:"지형 '해저/해안 암초' 해금에 필수인 장비."},
    equip_cold:{n:'방한 장비', d:"지형 '극지/설원 빙하' 해금에 필수인 장비."},
    equip_heat:{n:'내열 장비', d:"지형 '화산/용암 지대' 해금에 필수인 장비."},
    shop_time_n:'채굴 시간 연장', shop_time_d:'구매할 때마다 1회 채굴 시간이 +5초 증가합니다. 반복 구매 가능.',
    time_cur:'현재 1회 채굴 시간',
    shop_det_n:'탐지기 업그레이드', shop_det_d:'구매할 때마다 1회 광물 수가 +1개 증가, 최대 20개.',
    det_cur:'현재 1회 광물 수',
    shop_suit_n:'방호복', shop_suit_d:'방호복 1벌은 유독 광물(진사/우라늄/석면) 채집 10회를 보호하며, 다 쓰면 소멸됩니다. 여러 개 구매 가능.',
    suit_cur:'남은 방호 횟수',
    hookslot_title:'다중 클로 시스템', hookslot_desc:'동시에 발사되는 클로 개수를 업그레이드합니다, 최대 3개.',
    hookslot_cur:'현재 클로 개수', hookslot_buy:'클로 개수 업그레이드',
    claw_title:'클로 강화 (클로마다 독립적으로 업그레이드)',
    claw_n:'{n}번 클로', claw_locked:'아직 미해금',
    pierce_n:'관통 클로', pierce_d:'한 번의 투척으로 경로상의 모든 광물을 획득',
    reflect_n:'반사 클로', reflect_d:'허탕 시 한 번 튕겨서 재시도',
    buy_short:'업그레이드',
    faint_title:'채굴 중단', faint_msg:'유독 광물에 접촉하여 기절했습니다. 상점에서 방호 장비를 구매하세요.', faint_btn:'상점으로 이동',
    items_suffix:'개의 광물', each_suffix:'개당', unknown_short:'？？？',
    on_state:'ON', off_state:'OFF', testmode_label:'테스트 모드: ', lang_menu_title:'언어 선택',
  },
};

// Display names for the 8 terrains. Keyed by the original Chinese terrain
// name (which stays the internal id used throughout the game logic, e.g.
// TERRAINS[i].name, data-terrain attributes, TERRAIN_GEAR lookups).
// Use trName(terrain) in index.html to read the localized label.
const TERRAIN_NAME_I18N = {
  '平原/浅层土壤': {
    zh:'平原/浅层土壤', 'zh-TW':'平原/淺層土壤', en:'Plains / Shallow Soil', de:'Ebene / Flacher Boden',
    fr:'Plaine / Sol peu profond', ru:'Равнина / Мелкая почва', ja:'平原・浅い土壌',
    'pt-BR':'Planície / Solo Raso', es:'Llanura / Suelo Superficial', ko:'평원/얕은 토양',
  },
  '沼泽/湿地': {
    zh:'沼泽/湿地', 'zh-TW':'沼澤/濕地', en:'Swamp / Wetland', de:'Sumpf / Feuchtgebiet',
    fr:'Marais / Zone humide', ru:'Болото / Заболоченная местность', ja:'沼地・湿地',
    'pt-BR':'Pântano / Zona Úmida', es:'Pantano / Humedal', ko:'늪지/습지',
  },
  '山地/岩层': {
    zh:'山地/岩层', 'zh-TW':'山地/岩層', en:'Mountains / Rock Strata', de:'Gebirge / Gesteinsschichten',
    fr:'Montagne / Strates rocheuses', ru:'Горы / Скальные пласты', ja:'山地・岩層',
    'pt-BR':'Montanha / Camadas de Rocha', es:'Montaña / Estratos Rocosos', ko:'산지/암반층',
  },
  '沙漠': {
    zh:'沙漠', 'zh-TW':'沙漠', en:'Desert', de:'Wüste',
    fr:'Désert', ru:'Пустыня', ja:'砂漠',
    'pt-BR':'Deserto', es:'Desierto', ko:'사막',
  },
  '海底/海岸礁石': {
    zh:'海底/海岸礁石', 'zh-TW':'海底/海岸礁石', en:'Seabed / Coastal Reef', de:'Meeresboden / Küstenriff',
    fr:'Fond marin / Récif côtier', ru:'Морское дно / Прибрежный риф', ja:'海底・沿岸の岩礁',
    'pt-BR':'Fundo do Mar / Recife Costeiro', es:'Fondo Marino / Arrecife Costero', ko:'해저/해안 암초',
  },
  '极地/雪原冰川': {
    zh:'极地/雪原冰川', 'zh-TW':'極地/雪原冰川', en:'Polar / Icefield Glacier', de:'Polarregion / Gletscher',
    fr:'Pôle / Glacier', ru:'Полярный край / Ледник', ja:'極地・雪原氷河',
    'pt-BR':'Polar / Geleira', es:'Polar / Glaciar', ko:'극지/설원 빙하',
  },
  '火山/熔岩区': {
    zh:'火山/熔岩区', 'zh-TW':'火山/熔岩區', en:'Volcano / Lava Zone', de:'Vulkan / Lavazone',
    fr:'Volcan / Zone de lave', ru:'Вулкан / Лавовая зона', ja:'火山・溶岩地帯',
    'pt-BR':'Vulcão / Zona de Lava', es:'Volcán / Zona de Lava', ko:'화산/용암 지대',
  },
  '深层洞穴/矿脉核心': {
    zh:'深层洞穴/矿脉核心', 'zh-TW':'深層洞穴/礦脈核心', en:'Deep Cave / Vein Core', de:'Tiefe Höhle / Adernkern',
    fr:'Grotte profonde / Cœur du filon', ru:'Глубокая пещера / Ядро жилы', ja:'深層洞窟・鉱脈の核心',
    'pt-BR':'Caverna Profunda / Núcleo do Veio', es:'Cueva Profunda / Núcleo del Filón', ko:'심층 동굴/광맥 핵심',
  },
};
