/* ==========================================================================
   矿石收集者 Mine Collector — Localization file
   10 languages: zh, zh-TW, en, de, fr, ru, ja, pt-BR, es, ko
   Loaded before the main <script> in index.html — exposes:
     - window.I18N              UI text strings, keyed by language code
     - window.TERRAIN_NAME_I18N display names for terrains, keyed by the
                                 original (Chinese) terrain name used as the
                                 internal data id
   ========================================================================== */
const I18N = {
  zh: {
    title:'矿石收集者', subtitle:'MINE COLLECTOR', newgame:'开始游戏', continue_:'继续游戏', lang:'🌐 语言选择',
    tab_map:'地图', tab_shop:'商店', tab_warehouse:'仓库', tab_dex:'图鉴', tab_stats:'数据', exit:'回到主页', save_game:'保存游戏', stats_title:'数据', stats_desc:'按抓到过的次数从多到少排列，卖掉也不会减少。', stats_empty:'还没抓到过任何矿石，去挖矿吧！',
    map_title:'地形选择', map_desc:'挑选一处地形入场挖矿。解锁新地形需要累计发现足够多的矿物种类。',
    enter:'进入挖矿', free:'免费', locked_need:'累计发现矿物 {n}/{t} 种解锁', need_gear:'需要装备：',
    not_enough_gold:'金币不足',
    shop_title:'装备商店', shop_desc:'装备一次性永久购买；升级类可重复购买、效果叠加。',
    owned:'已拥有', buy:'购买', max_lv:'已满级',
    wh_title:'仓库', wh_desc:'挖到的矿石会先放进仓库，来这里手动卖出换金币。锁定的矿石不会被卖出。', sell_all:'出售全部', sell_one:'出售1个', wh_empty:'仓库空空如也，去挖矿吧！',
    total_value:'仓库库存价值',
    dex_title:'矿物图鉴', dex_desc:'记录你发现过的所有矿物。', dex_progress:'已发现', dex_other:'其他',
    all:'全部', industrial:'工业矿物', gem:'常见宝石矿物', crystal:'珍稀晶体矿物', fossil:'化石',
    unknown:'？？？未发现',
    haul_title:'本次收获', confirm:'确认入库，返回地图', total_earn:'总收益', remain:'剩余矿物', leave:'结束挖掘',
    hint:'点击画面或按【空格】发射钩爪',
    dex_close:'关闭',
    price:'售价', formula:'化学式', category:'分类', rarity:'稀有度', note:'备注',
    r_common:'普通', r_uncommon:'少见', r_rare:'稀有', r_epic:'史诗', r_legend:'传说',
    equip_winch:{n:'强化绞盘', d:'钩爪伸缩速度 +25%，挖矿效率更高。'},
    equip_light:{n:'轻量化钩爪', d:'所有矿物的拖拽重量 -20%，收绳更快。'},
    equip_luck:{n:'幸运探测仪', d:'史诗、传说级矿物的出现概率翻倍，多出的概率从该地形的普通矿物中平均扣除。'},
    equip_dive:{n:'潜水装备', d:'解锁地形【海底/海岸礁石】的必备装备。'},
    equip_cold:{n:'防寒装备', d:'解锁地形【极地/雪原冰川】的必备装备。'},
    equip_heat:{n:'耐热装备', d:'解锁地形【火山/熔岩区】的必备装备。'},
    shop_time_n:'延长开采时间', shop_time_d:'每次购买，单局挖矿时间 +5 秒，可重复购买。',
    time_cur:'当前单局时长',
    shop_det_n:'探矿仪升级', shop_det_d:'每次购买，单局矿物数量 +1 个，最多 20 个。',
    det_cur:'当前单局矿物数',
    shop_suit_n:'防护服', shop_suit_d:'一件可保护采集 10 次有毒矿物（辰砂/铀矿/石棉），用完即销毁，可多买堆叠。',
    suit_cur:'当前防护次数',
    hookslot_title:'多爪系统', hookslot_desc:'升级同时发射的钩爪数量，最多 3 只。',
    hookslot_cur:'当前钩爪数量', hookslot_buy:'升级钩爪数量',
    claw_title:'钩爪强化（每只钩爪独立升级）',
    claw_n:'{n}号爪', claw_locked:'尚未解锁',
    pierce_n:'穿透爪', pierce_d:'一次贯穿沿途所有矿物',
    reflect_n:'反射爪', reflect_d:'触底扑空后弹射一次再试',
    buy_short:'升级',
    faint_title:'采矿中断', faint_msg:'接触有毒矿物，你已晕倒。请去商店购买防护用品。', faint_btn:'前往商店',
    items_suffix:' 件矿物', each_suffix:'/个', unknown_short:'？？？',
    on_state:'开', off_state:'关', testmode_label:'测试模式：', lang_menu_title:'选择语言', gained:'获得：',
  },
  'zh-TW': {
    title:'礦石收集者', subtitle:'MINE COLLECTOR', newgame:'開始遊戲', continue_:'繼續遊戲', lang:'🌐 語言選擇',
    tab_map:'地圖', tab_shop:'商店', tab_warehouse:'倉庫', tab_dex:'圖鑑', tab_stats:'數據', exit:'回到主頁', save_game:'保存遊戲', stats_title:'數據', stats_desc:'依抓到過的次數由多到少排列，賣掉也不會減少。', stats_empty:'還沒抓到過任何礦石，去挖礦吧！',
    map_title:'地形選擇', map_desc:'挑選一處地形入場挖礦。解鎖新地形需要累計發現足夠多的礦物種類。',
    enter:'進入挖礦', free:'免費', locked_need:'累計發現礦物 {n}/{t} 種解鎖', need_gear:'需要裝備：',
    not_enough_gold:'金幣不足',
    shop_title:'裝備商店', shop_desc:'裝備一次性永久購買；升級類可重複購買、效果疊加。',
    owned:'已擁有', buy:'購買', max_lv:'已滿級',
    wh_title:'倉庫', wh_desc:'挖到的礦石會先放進倉庫，來這裡手動賣出換金幣。鎖定的礦石不會被賣出。', sell_all:'出售全部', sell_one:'出售1個', wh_empty:'倉庫空空如也，去挖礦吧！',
    total_value:'倉庫庫存價值',
    dex_title:'礦物圖鑑', dex_desc:'記錄你發現過的所有礦物。', dex_progress:'已發現', dex_other:'其他',
    all:'全部', industrial:'工業礦物', gem:'常見寶石礦物', crystal:'珍稀晶體礦物', fossil:'化石',
    unknown:'？？？未發現',
    haul_title:'本次收穫', confirm:'確認入庫，返回地圖', total_earn:'總收益', remain:'剩餘礦物', leave:'結束挖掘',
    hint:'點擊畫面或按【空格】發射鉤爪',
    dex_close:'關閉',
    price:'售價', formula:'化學式', category:'分類', rarity:'稀有度', note:'備註',
    r_common:'普通', r_uncommon:'少見', r_rare:'稀有', r_epic:'史詩', r_legend:'傳說',
    equip_winch:{n:'強化絞盤', d:'鉤爪伸縮速度 +25%，挖礦效率更高。'},
    equip_light:{n:'輕量化鉤爪', d:'所有礦物的拖曳重量 -20%，收繩更快。'},
    equip_luck:{n:'幸運探測儀', d:'史詩、傳說級礦物的出現機率翻倍，多出的機率從該地形的普通礦物中平均扣除。'},
    equip_dive:{n:'潛水裝備', d:'解鎖地形【海底/海岸礁石】的必備裝備。'},
    equip_cold:{n:'防寒裝備', d:'解鎖地形【極地/雪原冰川】的必備裝備。'},
    equip_heat:{n:'耐熱裝備', d:'解鎖地形【火山/熔岩區】的必備裝備。'},
    shop_time_n:'延長開採時間', shop_time_d:'每次購買，單局挖礦時間 +5 秒，可重複購買。',
    time_cur:'當前單局時長',
    shop_det_n:'探礦儀升級', shop_det_d:'每次購買，單局礦物數量 +1 個，最多 20 個。',
    det_cur:'當前單局礦物數',
    shop_suit_n:'防護服', shop_suit_d:'一件可保護採集 10 次有毒礦物（辰砂/鈾礦/石棉），用完即銷毀，可多買疊加。',
    suit_cur:'當前防護次數',
    hookslot_title:'多爪系統', hookslot_desc:'升級同時發射的鉤爪數量，最多 3 隻。',
    hookslot_cur:'當前鉤爪數量', hookslot_buy:'升級鉤爪數量',
    claw_title:'鉤爪強化（每隻鉤爪獨立升級）',
    claw_n:'{n}號爪', claw_locked:'尚未解鎖',
    pierce_n:'穿透爪', pierce_d:'一次貫穿沿途所有礦物',
    reflect_n:'反射爪', reflect_d:'觸底撲空後彈射一次再試',
    buy_short:'升級',
    faint_title:'採礦中斷', faint_msg:'接觸有毒礦物，你已暈倒。請去商店購買防護用品。', faint_btn:'前往商店',
    items_suffix:' 件礦物', each_suffix:'/個', unknown_short:'？？？',
    on_state:'開', off_state:'關', testmode_label:'測試模式：', lang_menu_title:'選擇語言', gained:'獲得：',
  },
  en: {
    title:'Mine Collector', subtitle:'矿石收集者', newgame:'New Game', continue_:'Continue', lang:'🌐 Language',
    tab_map:'Map', tab_shop:'Shop', tab_warehouse:'Warehouse', tab_dex:'Dex', tab_stats:'Stats', exit:'Home', save_game:'Save Game', stats_title:'Stats', stats_desc:'Ranked by how many times you\'ve ever caught each mineral \u2014 selling doesn\'t lower this.', stats_empty:'You haven\'t caught anything yet. Go mine something!',
    map_title:'Choose a Site', map_desc:'Pick a terrain to enter and mine. Unlock new terrains by discovering enough mineral species overall.',
    enter:'Enter Mine', free:'Free', locked_need:'Discover {n}/{t} species to unlock', need_gear:'Requires gear: ',
    not_enough_gold:'Not enough gold',
    shop_title:'Equipment Shop', shop_desc:'Gear is a one-time permanent purchase; upgrades are repeatable and stack.',
    owned:'Owned', buy:'Buy', max_lv:'Maxed',
    wh_title:'Warehouse', wh_desc:'Ore you dig up goes into the warehouse first — sell it here for gold. Locked ore cannot be sold.', sell_all:'Sell All', sell_one:'Sell 1', wh_empty:'Warehouse is empty. Go mine something!',
    total_value:'Warehouse stock value',
    dex_title:'Mineral Dex', dex_desc:'Everything you have ever discovered.', dex_progress:'Discovered', dex_other:'Other',
    all:'All', industrial:'Industrial', gem:'Common Gems', crystal:'Rare Crystals', fossil:'Fossils',
    unknown:'????? Undiscovered',
    haul_title:'Haul This Run', confirm:'Bank it & return to map', total_earn:'Total Earnings', remain:'Left', leave:'Leave Mine',
    hint:'Click or press SPACE to swing the hook',
    dex_close:'Close',
    price:'Price', formula:'Formula', category:'Category', rarity:'Rarity', note:'Note',
    r_common:'Common', r_uncommon:'Uncommon', r_rare:'Rare', r_epic:'Epic', r_legend:'Legendary',
    equip_winch:{n:'Reinforced Winch', d:'+25% hook extend/retract speed.'},
    equip_light:{n:'Light Claw', d:'-20% drag weight on all minerals — reel in faster.'},
    equip_luck:{n:'Lucky Detector', d:'Doubles epic and legendary mineral odds; the added chance is deducted evenly from that terrain\'s common-tier minerals.'},
    equip_dive:{n:'Diving Gear', d:'Required to unlock the Seabed/Reef terrain.'},
    equip_cold:{n:'Cold Gear', d:'Required to unlock the Polar Icefields terrain.'},
    equip_heat:{n:'Heat Suit', d:'Required to unlock the Volcanic Zone terrain.'},
    shop_time_n:'Extend Dig Time', shop_time_d:'Each purchase adds +5s to every mining run. Repeatable.',
    time_cur:'Current run length',
    shop_det_n:'Detector Upgrade', shop_det_d:'Each purchase gives +1 mineral per run, up to 20.',
    det_cur:'Current minerals/run',
    shop_suit_n:'Protective Suit', shop_suit_d:'Each suit protects 10 hazardous catches (cinnabar/uranium/asbestos), then is destroyed. Stackable.',
    suit_cur:'Charges remaining',
    hookslot_title:'Multi-Claw System', hookslot_desc:'Upgrade how many claws fire at once, up to 3.',
    hookslot_cur:'Active claws', hookslot_buy:'Upgrade claw count',
    claw_title:'Claw Enhancements (each claw upgrades independently)',
    claw_n:'Claw {n}', claw_locked:'Not unlocked',
    pierce_n:'Piercing Claw', pierce_d:'Grabs every mineral along its path in one throw',
    reflect_n:'Reflect Claw', reflect_d:'Bounces once and retries if it comes up empty',
    buy_short:'Upgrade',
    faint_title:'Mining Interrupted', faint_msg:'You touched a toxic mineral and passed out. Head to the shop for protective gear.', faint_btn:'Go to Shop',
    items_suffix:' items', each_suffix:'each', unknown_short:'???',
    on_state:'ON', off_state:'OFF', testmode_label:'Test Mode: ', lang_menu_title:'Select Language', gained:'Gained: ',
  },
  de: {
    title:'Minensammler', subtitle:'矿石收集者', newgame:'Neues Spiel', continue_:'Fortsetzen', lang:'🌐 Sprache',
    tab_map:'Karte', tab_shop:'Shop', tab_warehouse:'Lager', tab_dex:'Dex', tab_stats:'Statistik', exit:'Startseite', save_game:'Spiel speichern', stats_title:'Statistik', stats_desc:'Sortiert nach der H\u00e4ufigkeit, mit der du jedes Mineral je gefangen hast \u2014 Verkaufen verringert diesen Wert nicht.', stats_empty:'Du hast noch nichts gefangen. Geh sch\u00fcrfen!',
    map_title:'Gebiet wählen', map_desc:'Wähle ein Gelände zum Schürfen. Neue Gelände werden freigeschaltet, sobald du genug Mineralarten insgesamt entdeckt hast.',
    enter:'Mine betreten', free:'Kostenlos', locked_need:'{n}/{t} Arten entdecken zum Freischalten', need_gear:'Benötigt Ausrüstung: ',
    not_enough_gold:'Nicht genug Gold',
    shop_title:'Ausrüstungsshop', shop_desc:'Ausrüstung ist ein einmaliger, dauerhafter Kauf; Upgrades sind wiederholbar und stapelbar.',
    owned:'Im Besitz', buy:'Kaufen', max_lv:'Maximal',
    wh_title:'Lager', wh_desc:'Geförderte Erze landen zuerst im Lager – verkaufe sie hier für Gold. Gesperrte Erze können nicht verkauft werden.', sell_all:'Alle verkaufen', sell_one:'1 verkaufen', wh_empty:'Das Lager ist leer. Geh schürfen!',
    total_value:'Lagerwert',
    dex_title:'Mineral-Dex', dex_desc:'Alles, was du bisher entdeckt hast.', dex_progress:'Entdeckt', dex_other:'Sonstiges',
    all:'Alle', industrial:'Industriemineralien', gem:'Verbreitete Edelsteine', crystal:'Seltene Kristalle', fossil:'Fossilien',
    unknown:'????? Unentdeckt',
    haul_title:'Ausbeute dieser Runde', confirm:'Einlagern & zur Karte zurückkehren', total_earn:'Gesamteinnahmen', remain:'Übrig', leave:'Mine verlassen',
    hint:'Klicke oder drücke LEERTASTE, um den Haken zu schwingen',
    dex_close:'Schließen',
    price:'Preis', formula:'Formel', category:'Kategorie', rarity:'Seltenheit', note:'Notiz',
    r_common:'Gewöhnlich', r_uncommon:'Ungewöhnlich', r_rare:'Selten', r_epic:'Episch', r_legend:'Legendär',
    equip_winch:{n:'Verstärkte Winde', d:'+25% Geschwindigkeit beim Aus-/Einfahren des Hakens.'},
    equip_light:{n:'Leichter Greifer', d:'-20% Zuggewicht bei allen Mineralien – schnelleres Einholen.'},
    equip_luck:{n:'Glücksdetektor', d:'Verdoppelt die Chance auf epische und legendäre Mineralien; die zusätzliche Chance wird gleichmäßig von den gewöhnlichen Mineralien dieses Geländes abgezogen.'},
    equip_dive:{n:'Tauchausrüstung', d:'Erforderlich, um das Gelände Meeresboden/Riff freizuschalten.'},
    equip_cold:{n:'Kälteschutz', d:'Erforderlich, um das Gelände Polare Eisfelder freizuschalten.'},
    equip_heat:{n:'Hitzeschutzanzug', d:'Erforderlich, um das Gelände Vulkanzone freizuschalten.'},
    shop_time_n:'Grabzeit verlängern', shop_time_d:'Jeder Kauf verlängert jede Mining-Runde um +5 Sek. Wiederholbar.',
    time_cur:'Aktuelle Rundenlänge',
    shop_det_n:'Detektor-Upgrade', shop_det_d:'Jeder Kauf gibt +1 Mineral pro Runde, bis zu 20.',
    det_cur:'Aktuelle Mineralien/Runde',
    shop_suit_n:'Schutzanzug', shop_suit_d:'Jeder Anzug schützt bei 10 gefährlichen Fängen (Zinnober/Uran/Asbest) und wird danach zerstört. Stapelbar.',
    suit_cur:'Verbleibende Ladungen',
    hookslot_title:'Mehrfach-Greifer-System', hookslot_desc:'Erhöhe die Anzahl gleichzeitig abgefeuerter Greifer, bis zu 3.',
    hookslot_cur:'Aktive Greifer', hookslot_buy:'Greiferanzahl aufwerten',
    claw_title:'Greifer-Verbesserungen (jeder Greifer wird unabhängig aufgewertet)',
    claw_n:'Greifer {n}', claw_locked:'Nicht freigeschaltet',
    pierce_n:'Durchdringungsgreifer', pierce_d:'Erfasst mit einem Wurf alle Mineralien entlang des Wegs',
    reflect_n:'Reflexgreifer', reflect_d:'Prallt bei leerem Fang einmal ab und versucht es erneut',
    buy_short:'Aufwerten',
    faint_title:'Abbau unterbrochen', faint_msg:'Du hast ein giftiges Mineral berührt und bist ohnmächtig geworden. Geh zum Shop und kaufe Schutzausrüstung.', faint_btn:'Zum Shop',
    items_suffix:' Objekte', each_suffix:'je Stück', unknown_short:'???',
    on_state:'AN', off_state:'AUS', testmode_label:'Testmodus: ', lang_menu_title:'Sprache wählen', gained:'Erhalten: ',
  },
  fr: {
    title:'Collectionneur de Mines', subtitle:'矿石收集者', newgame:'Nouvelle partie', continue_:'Continuer', lang:'🌐 Langue',
    tab_map:'Carte', tab_shop:'Boutique', tab_warehouse:'Entrepôt', tab_dex:'Dex', tab_stats:'Stats', exit:'Accueil', save_game:'Sauvegarder', stats_title:'Statistiques', stats_desc:'Class\u00e9 selon le nombre de fois o\u00f9 vous avez attrap\u00e9 chaque min\u00e9ral \u2014 la vente ne r\u00e9duit pas ce nombre.', stats_empty:'Vous n\'avez encore rien attrap\u00e9. Allez miner !',
    map_title:'Choisir un site', map_desc:"Choisissez un terrain pour miner. Débloquez de nouveaux terrains en découvrant suffisamment d'espèces de minéraux au total.",
    enter:'Entrer dans la mine', free:'Gratuit', locked_need:'Découvrez {n}/{t} espèces pour débloquer', need_gear:'Équipement requis : ',
    not_enough_gold:'Or insuffisant',
    shop_title:"Boutique d'équipement", shop_desc:"L'équipement est un achat permanent unique ; les améliorations sont répétables et cumulables.",
    owned:'Possédé', buy:'Acheter', max_lv:'Maximum',
    wh_title:'Entrepôt', wh_desc:"Le minerai extrait va d'abord dans l'entrepôt — vendez-le ici contre de l'or. Le minerai verrouillé ne peut pas être vendu.", sell_all:'Tout vendre', sell_one:'Vendre 1', wh_empty:'Entrepôt vide. Allez miner !',
    total_value:'Valeur du stock',
    dex_title:'Dex des minéraux', dex_desc:"Tout ce que vous avez découvert jusqu'à présent.", dex_progress:'Découverts', dex_other:'Autres',
    all:'Tous', industrial:'Minéraux industriels', gem:'Pierres précieuses courantes', crystal:'Cristaux rares', fossil:'Fossiles',
    unknown:'????? Non découvert',
    haul_title:'Butin de cette partie', confirm:'Stocker et retourner à la carte', total_earn:'Gains totaux', remain:'Restant', leave:'Quitter la mine',
    hint:'Cliquez ou appuyez sur ESPACE pour lancer le grappin',
    dex_close:'Fermer',
    price:'Prix', formula:'Formule', category:'Catégorie', rarity:'Rareté', note:'Remarque',
    r_common:'Commun', r_uncommon:'Peu commun', r_rare:'Rare', r_epic:'Épique', r_legend:'Légendaire',
    equip_winch:{n:'Treuil renforcé', d:"+25% de vitesse d'extension/rétraction du grappin."},
    equip_light:{n:'Grappin léger', d:'-20% de poids de traction sur tous les minéraux — remontée plus rapide.'},
    equip_luck:{n:'Détecteur chanceux', d:'Double la probabilité des minéraux épiques et légendaires ; la probabilité ajoutée est déduite également des minéraux communs de ce terrain.'},
    equip_dive:{n:'Équipement de plongée', d:'Requis pour débloquer le terrain Fond marin/Récif.'},
    equip_cold:{n:'Équipement grand froid', d:'Requis pour débloquer le terrain Glacier polaire.'},
    equip_heat:{n:'Combinaison thermique', d:'Requis pour débloquer le terrain Zone volcanique.'},
    shop_time_n:'Prolonger le temps de forage', shop_time_d:'Chaque achat ajoute +5 s à chaque partie de minage. Répétable.',
    time_cur:'Durée actuelle de la partie',
    shop_det_n:'Amélioration du détecteur', shop_det_d:"Chaque achat donne +1 minéral par partie, jusqu'à 20.",
    det_cur:'Minéraux actuels/partie',
    shop_suit_n:'Combinaison de protection', shop_suit_d:'Chaque combinaison protège 10 prises dangereuses (cinabre/uranium/amiante), puis est détruite. Cumulable.',
    suit_cur:'Charges restantes',
    hookslot_title:'Système multi-grappins', hookslot_desc:'Augmentez le nombre de grappins lancés simultanément, jusqu\'à 3.',
    hookslot_cur:'Grappins actifs', hookslot_buy:'Améliorer le nombre de grappins',
    claw_title:"Améliorations des grappins (chaque grappin s'améliore indépendamment)",
    claw_n:'Grappin {n}', claw_locked:'Non débloqué',
    pierce_n:'Grappin perforant', pierce_d:'Attrape tous les minéraux sur son passage en un seul lancer',
    reflect_n:'Grappin réflecteur', reflect_d:'Rebondit une fois et réessaie si vide',
    buy_short:'Améliorer',
    faint_title:'Extraction interrompue', faint_msg:"Vous avez touché un minéral toxique et vous êtes évanoui. Rendez-vous à la boutique pour acheter de l'équipement de protection.", faint_btn:'Aller à la boutique',
    items_suffix:' objets', each_suffix:'chacun', unknown_short:'???',
    on_state:'ON', off_state:'OFF', testmode_label:'Mode test : ', lang_menu_title:'Choisir la langue', gained:'Obtenu : ',
  },
  ru: {
    title:'Коллекционер Шахт', subtitle:'矿石收集者', newgame:'Новая игра', continue_:'Продолжить', lang:'🌐 Язык',
    tab_map:'Карта', tab_shop:'Магазин', tab_warehouse:'Склад', tab_dex:'Дех', tab_stats:'Статистика', exit:'На главную', save_game:'Сохранить игру', stats_title:'Статистика', stats_desc:'Отсортировано по тому, сколько раз вы поймали каждый минерал \u2014 продажа не уменьшает это число.', stats_empty:'Вы пока ничего не поймали. Идите добывать!',
    map_title:'Выбор участка', map_desc:'Выберите местность для добычи. Новые местности открываются по мере обнаружения достаточного числа видов минералов.',
    enter:'Войти в шахту', free:'Бесплатно', locked_need:'Откройте {n}/{t} видов для разблокировки', need_gear:'Необходимо снаряжение: ',
    not_enough_gold:'Недостаточно золота',
    shop_title:'Магазин снаряжения', shop_desc:'Снаряжение покупается один раз навсегда; улучшения можно покупать многократно, эффекты суммируются.',
    owned:'Есть', buy:'Купить', max_lv:'Максимум',
    wh_title:'Склад', wh_desc:'Добытая руда сначала попадает на склад — продавайте её здесь за золото. Заблокированную руду продать нельзя.', sell_all:'Продать всё', sell_one:'Продать 1', wh_empty:'Склад пуст. Идите добывать!',
    total_value:'Стоимость запасов склада',
    dex_title:'Справочник минералов', dex_desc:'Всё, что вы когда-либо находили.', dex_progress:'Найдено', dex_other:'Прочее',
    all:'Все', industrial:'Промышленные минералы', gem:'Обычные драгоценные камни', crystal:'Редкие кристаллы', fossil:'Окаменелости',
    unknown:'????? Не найдено',
    haul_title:'Добыча за этот заход', confirm:'Сохранить и вернуться на карту', total_earn:'Общий доход', remain:'Осталось', leave:'Покинуть шахту',
    hint:'Нажмите или используйте ПРОБЕЛ, чтобы забросить крюк',
    dex_close:'Закрыть',
    price:'Цена', formula:'Формула', category:'Категория', rarity:'Редкость', note:'Заметка',
    r_common:'Обычный', r_uncommon:'Необычный', r_rare:'Редкий', r_epic:'Эпический', r_legend:'Легендарный',
    equip_winch:{n:'Усиленная лебёдка', d:'Скорость выдвижения/втягивания крюка +25%.'},
    equip_light:{n:'Лёгкий захват', d:'Вес перетаскивания всех минералов −20% — быстрее сматывание.'},
    equip_luck:{n:'Счастливый детектор', d:'Удваивает шанс на эпические и легендарные минералы; добавленный шанс поровну вычитается из обычных минералов этой местности.'},
    equip_dive:{n:'Водолазное снаряжение', d:'Необходимо для открытия местности «Морское дно/риф».'},
    equip_cold:{n:'Снаряжение от холода', d:'Необходимо для открытия местности «Полярные ледники».'},
    equip_heat:{n:'Термокостюм', d:'Необходимо для открытия местности «Вулканическая зона».'},
    shop_time_n:'Увеличить время добычи', shop_time_d:'Каждая покупка добавляет +5 сек к каждому заходу. Можно покупать многократно.',
    time_cur:'Текущая длительность захода',
    shop_det_n:'Улучшение детектора', shop_det_d:'Каждая покупка даёт +1 минерал за заход, максимум 20.',
    det_cur:'Текущее число минералов/заход',
    shop_suit_n:'Защитный костюм', shop_suit_d:'Один костюм защищает от 10 опасных находок (киноварь/уран/асбест), затем уничтожается. Можно накапливать.',
    suit_cur:'Осталось зарядов',
    hookslot_title:'Система нескольких крюков', hookslot_desc:'Увеличьте число одновременно выстреливаемых крюков, максимум 3.',
    hookslot_cur:'Активных крюков', hookslot_buy:'Улучшить число крюков',
    claw_title:'Улучшения крюков (каждый крюк улучшается отдельно)',
    claw_n:'Крюк {n}', claw_locked:'Не разблокирован',
    pierce_n:'Пронзающий крюк', pierce_d:'Захватывает все минералы на пути за один бросок',
    reflect_n:'Отражающий крюк', reflect_d:'При промахе один раз отскакивает и пробует снова',
    buy_short:'Улучшить',
    faint_title:'Добыча прервана', faint_msg:'Вы коснулись токсичного минерала и потеряли сознание. Отправляйтесь в магазин за защитным снаряжением.', faint_btn:'В магазин',
    items_suffix:' предм.', each_suffix:'за шт.', unknown_short:'???',
    on_state:'ВКЛ', off_state:'ВЫКЛ', testmode_label:'Тестовый режим: ', lang_menu_title:'Выбор языка', gained:'Получено: ',
  },
  ja: {
    title:'マインコレクター', subtitle:'矿石收集者', newgame:'新しく始める', continue_:'続ける', lang:'🌐 言語',
    tab_map:'マップ', tab_shop:'ショップ', tab_warehouse:'倉庫', tab_dex:'図鑑', tab_stats:'データ', exit:'ホームへ', save_game:'ゲームを保存', stats_title:'データ', stats_desc:'これまでに捕まえた回数の多い順に並んでいます。売却しても回数は減りません。', stats_empty:'まだ何も捕まえていません。採掘に行きましょう！',
    map_title:'採掘地を選ぶ', map_desc:'採掘する地形を選んでください。累計で十分な種類の鉱物を発見すると新しい地形が解放されます。',
    enter:'採掘へ', free:'無料', locked_need:'鉱物を{n}/{t}種発見で解放', need_gear:'必要装備：',
    not_enough_gold:'ゴールドが足りません',
    shop_title:'装備ショップ', shop_desc:'装備は一度きりの永久購入、アップグレードは繰り返し購入でき効果が重なります。',
    owned:'所持済み', buy:'購入', max_lv:'最大',
    wh_title:'倉庫', wh_desc:'採掘した鉱石はまず倉庫に入ります。ここで手動で売ってゴールドに換えましょう。ロックした鉱石は売却されません。', sell_all:'全部売却', sell_one:'1個売却', wh_empty:'倉庫は空っぽです。採掘に行きましょう！',
    total_value:'倉庫在庫の価値',
    dex_title:'鉱物図鑑', dex_desc:'これまでに発見したすべての鉱物。', dex_progress:'発見済み', dex_other:'その他',
    all:'すべて', industrial:'工業鉱物', gem:'一般宝石鉱物', crystal:'希少結晶鉱物', fossil:'化石',
    unknown:'？？？未発見',
    haul_title:'今回の収穫', confirm:'収納してマップへ戻る', total_earn:'合計収益', remain:'残り', leave:'採掘を終了',
    hint:'画面をクリックまたは【スペース】キーでフックを発射',
    dex_close:'閉じる',
    price:'売値', formula:'化学式', category:'分類', rarity:'レア度', note:'備考',
    r_common:'コモン', r_uncommon:'アンコモン', r_rare:'レア', r_epic:'エピック', r_legend:'レジェンド',
    equip_winch:{n:'強化ウインチ', d:'フックの伸縮速度が+25%になる。'},
    equip_light:{n:'軽量化フック', d:'すべての鉱物のドラッグ重量が-20%になり、巻き取りが速くなる。'},
    equip_luck:{n:'幸運探知機', d:'エピック・レジェンド級鉱物の出現確率が2倍になる。増えた分はその地形のコモン鉱物から均等に差し引かれる。'},
    equip_dive:{n:'潜水装備', d:'地形「海底・沿岸の岩礁」の解放に必要。'},
    equip_cold:{n:'防寒装備', d:'地形「極地・雪原氷河」の解放に必要。'},
    equip_heat:{n:'耐熱装備', d:'地形「火山・溶岩地帯」の解放に必要。'},
    shop_time_n:'採掘時間延長', shop_time_d:'購入ごとに1回の採掘時間が+5秒。何度でも購入可能。',
    time_cur:'現在の1回の制限時間',
    shop_det_n:'探鉱機アップグレード', shop_det_d:'購入ごとに1回の鉱物数が+1個、最大20個まで。',
    det_cur:'現在の1回あたりの鉱物数',
    shop_suit_n:'防護服', shop_suit_d:'1着で有毒鉱物（辰砂／ウラン鉱／石綿）の採取を10回保護し、使い切ると消滅。複数所持可。',
    suit_cur:'現在の保護回数',
    hookslot_title:'マルチフックシステム', hookslot_desc:'同時に発射できるフックの数をアップグレード、最大3本。',
    hookslot_cur:'現在のフック数', hookslot_buy:'フック数をアップグレード',
    claw_title:'フック強化（各フックは個別にアップグレード）',
    claw_n:'{n}号フック', claw_locked:'未解放',
    pierce_n:'貫通フック', pierce_d:'一投で経路上のすべての鉱物を回収する',
    reflect_n:'反射フック', reflect_d:'空振り時に一度跳ね返って再挑戦する',
    buy_short:'アップグレード',
    faint_title:'採掘中断', faint_msg:'有毒鉱物に触れて気絶しました。ショップで防護装備を購入してください。', faint_btn:'ショップへ',
    items_suffix:'個の鉱物', each_suffix:'/個', unknown_short:'？？？',
    on_state:'オン', off_state:'オフ', testmode_label:'テストモード：', lang_menu_title:'言語を選択', gained:'獲得：',
  },
  'pt-BR': {
    title:'Colecionador de Minas', subtitle:'矿石收集者', newgame:'Novo Jogo', continue_:'Continuar', lang:'🌐 Idioma',
    tab_map:'Mapa', tab_shop:'Loja', tab_warehouse:'Armazém', tab_dex:'Dex', tab_stats:'Estatísticas', exit:'Início', save_game:'Salvar Jogo', stats_title:'Estatísticas', stats_desc:'Classificado por quantas vezes você já capturou cada mineral \u2014 vender não reduz esse número.', stats_empty:'Você ainda não capturou nada. Vá minerar algo!',
    map_title:'Escolher Local', map_desc:'Escolha um terreno para minerar. Desbloqueie novos terrenos descobrindo espécies de minerais suficientes no total.',
    enter:'Entrar na Mina', free:'Grátis', locked_need:'Descubra {n}/{t} espécies para desbloquear', need_gear:'Equipamento necessário: ',
    not_enough_gold:'Ouro insuficiente',
    shop_title:'Loja de Equipamentos', shop_desc:'Equipamentos são uma compra única e permanente; upgrades são repetíveis e acumuláveis.',
    owned:'Possuído', buy:'Comprar', max_lv:'Máximo',
    wh_title:'Armazém', wh_desc:'O minério extraído vai primeiro para o armazém — venda-o aqui por ouro. Minério bloqueado não pode ser vendido.', sell_all:'Vender Tudo', sell_one:'Vender 1', wh_empty:'O armazém está vazio. Vá minerar algo!',
    total_value:'Valor do estoque do armazém',
    dex_title:'Dex de Minerais', dex_desc:'Tudo o que você já descobriu.', dex_progress:'Descobertos', dex_other:'Outros',
    all:'Todos', industrial:'Minerais Industriais', gem:'Gemas Comuns', crystal:'Cristais Raros', fossil:'Fósseis',
    unknown:'????? Não descoberto',
    haul_title:'Coleta desta Partida', confirm:'Guardar e voltar ao mapa', total_earn:'Ganhos Totais', remain:'Restante', leave:'Sair da Mina',
    hint:'Clique ou pressione ESPAÇO para lançar o gancho',
    dex_close:'Fechar',
    price:'Preço', formula:'Fórmula', category:'Categoria', rarity:'Raridade', note:'Nota',
    r_common:'Comum', r_uncommon:'Incomum', r_rare:'Raro', r_epic:'Épico', r_legend:'Lendário',
    equip_winch:{n:'Guincho Reforçado', d:'+25% de velocidade de extensão/retração do gancho.'},
    equip_light:{n:'Garra Leve', d:'-20% de peso de arrasto em todos os minerais — recolhe mais rápido.'},
    equip_luck:{n:'Detector da Sorte', d:'Dobra a chance de minerais épicos e lendários; a chance adicionada é deduzida igualmente dos minerais comuns deste terreno.'},
    equip_dive:{n:'Equipamento de Mergulho', d:'Necessário para desbloquear o terreno Fundo do Mar/Recife.'},
    equip_cold:{n:'Equipamento contra Frio', d:'Necessário para desbloquear o terreno Geleira Polar.'},
    equip_heat:{n:'Traje Térmico', d:'Necessário para desbloquear o terreno Zona Vulcânica.'},
    shop_time_n:'Estender Tempo de Escavação', shop_time_d:'Cada compra adiciona +5s a cada partida de mineração. Repetível.',
    time_cur:'Duração atual da partida',
    shop_det_n:'Upgrade do Detector', shop_det_d:'Cada compra dá +1 mineral por partida, até 20.',
    det_cur:'Minerais atuais/partida',
    shop_suit_n:'Traje de Proteção', shop_suit_d:'Cada traje protege 10 capturas perigosas (cinábrio/urânio/amianto), depois é destruído. Acumulável.',
    suit_cur:'Cargas restantes',
    hookslot_title:'Sistema Multi-Garra', hookslot_desc:'Aumente quantas garras disparam ao mesmo tempo, até 3.',
    hookslot_cur:'Garras ativas', hookslot_buy:'Melhorar número de garras',
    claw_title:'Melhorias das Garras (cada garra é aprimorada independentemente)',
    claw_n:'Garra {n}', claw_locked:'Não desbloqueada',
    pierce_n:'Garra Perfurante', pierce_d:'Captura todos os minerais no caminho em um único lançamento',
    reflect_n:'Garra Reflexiva', reflect_d:'Quica uma vez e tenta de novo se voltar vazia',
    buy_short:'Melhorar',
    faint_title:'Mineração Interrompida', faint_msg:'Você tocou em um mineral tóxico e desmaiou. Vá até a loja comprar equipamento de proteção.', faint_btn:'Ir para a Loja',
    items_suffix:' itens', each_suffix:'cada', unknown_short:'???',
    on_state:'LIGADO', off_state:'DESLIGADO', testmode_label:'Modo de teste: ', lang_menu_title:'Selecionar idioma', gained:'Obtido: ',
  },
  es: {
    title:'Coleccionista de Minas', subtitle:'矿石收集者', newgame:'Nueva Partida', continue_:'Continuar', lang:'🌐 Idioma',
    tab_map:'Mapa', tab_shop:'Tienda', tab_warehouse:'Almacén', tab_dex:'Dex', tab_stats:'Estadísticas', exit:'Inicio', save_game:'Guardar Partida', stats_title:'Estadísticas', stats_desc:'Ordenado por cuántas veces has capturado cada mineral \u2014 venderlo no reduce este número.', stats_empty:'Aún no has capturado nada. ¡Ve a minar algo!',
    map_title:'Elegir Terreno', map_desc:'Elige un terreno para entrar y minar. Desbloquea nuevos terrenos descubriendo suficientes especies de minerales en total.',
    enter:'Entrar a la Mina', free:'Gratis', locked_need:'Descubre {n}/{t} especies para desbloquear', need_gear:'Equipo requerido: ',
    not_enough_gold:'Oro insuficiente',
    shop_title:'Tienda de Equipo', shop_desc:'El equipo es una compra única y permanente; las mejoras son repetibles y acumulables.',
    owned:'Adquirido', buy:'Comprar', max_lv:'Al máximo',
    wh_title:'Almacén', wh_desc:'El mineral que extraes va primero al almacén; véndelo aquí por oro. El mineral bloqueado no se puede vender.', sell_all:'Vender Todo', sell_one:'Vender 1', wh_empty:'El almacén está vacío. ¡Ve a minar algo!',
    total_value:'Valor del inventario del almacén',
    dex_title:'Dex de Minerales', dex_desc:'Todo lo que has descubierto hasta ahora.', dex_progress:'Descubiertos', dex_other:'Otros',
    all:'Todos', industrial:'Minerales Industriales', gem:'Gemas Comunes', crystal:'Cristales Raros', fossil:'Fósiles',
    unknown:'????? Sin descubrir',
    haul_title:'Botín de esta Partida', confirm:'Guardar y volver al mapa', total_earn:'Ganancias Totales', remain:'Restante', leave:'Salir de la Mina',
    hint:'Haz clic o presiona ESPACIO para lanzar el gancho',
    dex_close:'Cerrar',
    price:'Precio', formula:'Fórmula', category:'Categoría', rarity:'Rareza', note:'Nota',
    r_common:'Común', r_uncommon:'Poco común', r_rare:'Raro', r_epic:'Épico', r_legend:'Legendario',
    equip_winch:{n:'Torno Reforzado', d:'+25% de velocidad al extender/retraer el gancho.'},
    equip_light:{n:'Garra Liviana', d:'-20% de peso de arrastre en todos los minerales; recoges más rápido.'},
    equip_luck:{n:'Detector de la Suerte', d:'Duplica la probabilidad de minerales épicos y legendarios; la probabilidad añadida se deduce por igual de los minerales comunes de ese terreno.'},
    equip_dive:{n:'Equipo de Buceo', d:'Necesario para desbloquear el terreno Fondo Marino/Arrecife.'},
    equip_cold:{n:'Equipo Anticongelante', d:'Necesario para desbloquear el terreno Glaciar Polar.'},
    equip_heat:{n:'Traje Térmico', d:'Necesario para desbloquear el terreno Zona Volcánica.'},
    shop_time_n:'Extender Tiempo de Excavación', shop_time_d:'Cada compra añade +5s a cada partida de minería. Repetible.',
    time_cur:'Duración actual de la partida',
    shop_det_n:'Mejora del Detector', shop_det_d:'Cada compra otorga +1 mineral por partida, hasta 20.',
    det_cur:'Minerales actuales/partida',
    shop_suit_n:'Traje Protector', shop_suit_d:'Cada traje protege 10 capturas peligrosas (cinabrio/uranio/asbesto), luego se destruye. Acumulable.',
    suit_cur:'Cargas restantes',
    hookslot_title:'Sistema Multi-Garra', hookslot_desc:'Aumenta cuántas garras se disparan a la vez, hasta 3.',
    hookslot_cur:'Garras activas', hookslot_buy:'Mejorar cantidad de garras',
    claw_title:'Mejoras de Garra (cada garra mejora de forma independiente)',
    claw_n:'Garra {n}', claw_locked:'No desbloqueada',
    pierce_n:'Garra Perforante', pierce_d:'Captura todos los minerales en su trayectoria en un solo lanzamiento',
    reflect_n:'Garra Reflectante', reflect_d:'Rebota una vez y vuelve a intentarlo si vuelve vacía',
    buy_short:'Mejorar',
    faint_title:'Minería Interrumpida', faint_msg:'Tocaste un mineral tóxico y te desmayaste. Ve a la tienda a comprar equipo de protección.', faint_btn:'Ir a la Tienda',
    items_suffix:' objetos', each_suffix:'c/u', unknown_short:'???',
    on_state:'ACTIVADO', off_state:'DESACTIVADO', testmode_label:'Modo de prueba: ', lang_menu_title:'Seleccionar idioma', gained:'Obtenido: ',
  },
  ko: {
    title:'마인 컬렉터', subtitle:'矿石收集者', newgame:'새 게임', continue_:'이어하기', lang:'🌐 언어',
    tab_map:'지도', tab_shop:'상점', tab_warehouse:'창고', tab_dex:'도감', tab_stats:'데이터', exit:'홈으로', save_game:'게임 저장', stats_title:'데이터', stats_desc:'지금까지 잡은 횟수가 많은 순으로 정렬됩니다. 판매해도 이 횟수는 줄지 않습니다.', stats_empty:'아직 아무것도 잡지 못했습니다. 채굴하러 가세요!',
    map_title:'지형 선택', map_desc:'채굴할 지형을 선택하세요. 누적으로 충분한 종류의 광물을 발견하면 새로운 지형이 해금됩니다.',
    enter:'채굴 입장', free:'무료', locked_need:'광물 {n}/{t}종 발견 시 해금', need_gear:'필요 장비: ',
    not_enough_gold:'골드가 부족합니다',
    shop_title:'장비 상점', shop_desc:'장비는 1회 영구 구매이며, 업그레이드는 반복 구매가 가능하고 효과가 누적됩니다.',
    owned:'보유 중', buy:'구매', max_lv:'최대 레벨',
    wh_title:'창고', wh_desc:'채굴한 광석은 먼저 창고에 들어갑니다. 여기서 직접 팔아 골드로 바꾸세요. 잠긴 광석은 판매되지 않습니다.', sell_all:'전부 판매', sell_one:'1개 판매', wh_empty:'창고가 비어 있습니다. 채굴하러 가세요!',
    total_value:'창고 재고 가치',
    dex_title:'광물 도감', dex_desc:'지금까지 발견한 모든 광물입니다.', dex_progress:'발견됨', dex_other:'기타',
    all:'전체', industrial:'산업 광물', gem:'일반 보석 광물', crystal:'희귀 결정 광물', fossil:'화석',
    unknown:'????? 미발견',
    haul_title:'이번 채굴 수확', confirm:'입고하고 지도로 돌아가기', total_earn:'총 수익', remain:'남은 광물', leave:'채굴 종료',
    hint:'화면을 클릭하거나 【스페이스】를 눌러 고리를 발사하세요',
    dex_close:'닫기',
    price:'판매가', formula:'화학식', category:'분류', rarity:'희귀도', note:'비고',
    r_common:'일반', r_uncommon:'희소', r_rare:'희귀', r_epic:'에픽', r_legend:'전설',
    equip_winch:{n:'강화 윈치', d:'고리 신축 속도 +25%.'},
    equip_light:{n:'경량 클로', d:'모든 광물의 견인 무게 -20%, 회수 속도 향상.'},
    equip_luck:{n:'행운 탐지기', d:'에픽·전설 등급 광물 출현 확률이 2배로 증가하며, 늘어난 확률만큼 해당 지형의 일반 등급 광물에서 균등하게 차감됩니다.'},
    equip_dive:{n:'잠수 장비', d:"지형 '해저/해안 암초' 해금에 필수인 장비."},
    equip_cold:{n:'방한 장비', d:"지형 '극지/설원 빙하' 해금에 필수인 장비."},
    equip_heat:{n:'내열 장비', d:"지형 '화산/용암 지대' 해금에 필수인 장비."},
    shop_time_n:'채굴 시간 연장', shop_time_d:'구매할 때마다 1회 채굴 시간이 +5초 증가합니다. 반복 구매 가능.',
    time_cur:'현재 1회 채굴 시간',
    shop_det_n:'탐지기 업그레이드', shop_det_d:'구매할 때마다 1회 광물 수가 +1개 증가, 최대 20개.',
    det_cur:'현재 1회 광물 수',
    shop_suit_n:'방호복', shop_suit_d:'방호복 1벌은 유독 광물(진사/우라늄/석면) 채집 10회를 보호하며, 다 쓰면 소멸됩니다. 여러 개 구매 가능.',
    suit_cur:'남은 방호 횟수',
    hookslot_title:'다중 클로 시스템', hookslot_desc:'동시에 발사되는 클로 개수를 업그레이드합니다, 최대 3개.',
    hookslot_cur:'현재 클로 개수', hookslot_buy:'클로 개수 업그레이드',
    claw_title:'클로 강화 (클로마다 독립적으로 업그레이드)',
    claw_n:'{n}번 클로', claw_locked:'아직 미해금',
    pierce_n:'관통 클로', pierce_d:'한 번의 투척으로 경로상의 모든 광물을 획득',
    reflect_n:'반사 클로', reflect_d:'허탕 시 한 번 튕겨서 재시도',
    buy_short:'업그레이드',
    faint_title:'채굴 중단', faint_msg:'유독 광물에 접촉하여 기절했습니다. 상점에서 방호 장비를 구매하세요.', faint_btn:'상점으로 이동',
    items_suffix:'개의 광물', each_suffix:'개당', unknown_short:'？？？',
    on_state:'ON', off_state:'OFF', testmode_label:'테스트 모드: ', lang_menu_title:'언어 선택', gained:'획득: ',
  },
};

// Display names for the 8 terrains. Keyed by the original Chinese terrain
// name (which stays the internal id used throughout the game logic, e.g.
// TERRAINS[i].name, data-terrain attributes, TERRAIN_GEAR lookups).
// Use trName(terrain) in index.html to read the localized label.
const TERRAIN_NAME_I18N = {
  '平原/浅层土壤': {
    zh:'平原/浅层土壤', 'zh-TW':'平原/淺層土壤', en:'Plains / Shallow Soil', de:'Ebene / Flacher Boden',
    fr:'Plaine / Sol peu profond', ru:'Равнина / Мелкая почва', ja:'平原・浅い土壌',
    'pt-BR':'Planície / Solo Raso', es:'Llanura / Suelo Superficial', ko:'평원/얕은 토양',
  },
  '沼泽/湿地': {
    zh:'沼泽/湿地', 'zh-TW':'沼澤/濕地', en:'Swamp / Wetland', de:'Sumpf / Feuchtgebiet',
    fr:'Marais / Zone humide', ru:'Болото / Заболоченная местность', ja:'沼地・湿地',
    'pt-BR':'Pântano / Zona Úmida', es:'Pantano / Humedal', ko:'늪지/습지',
  },
  '山地/岩层': {
    zh:'山地/岩层', 'zh-TW':'山地/岩層', en:'Mountains / Rock Strata', de:'Gebirge / Gesteinsschichten',
    fr:'Montagne / Strates rocheuses', ru:'Горы / Скальные пласты', ja:'山地・岩層',
    'pt-BR':'Montanha / Camadas de Rocha', es:'Montaña / Estratos Rocosos', ko:'산지/암반층',
  },
  '沙漠': {
    zh:'沙漠', 'zh-TW':'沙漠', en:'Desert', de:'Wüste',
    fr:'Désert', ru:'Пустыня', ja:'砂漠',
    'pt-BR':'Deserto', es:'Desierto', ko:'사막',
  },
  '海底/海岸礁石': {
    zh:'海底/海岸礁石', 'zh-TW':'海底/海岸礁石', en:'Seabed / Coastal Reef', de:'Meeresboden / Küstenriff',
    fr:'Fond marin / Récif côtier', ru:'Морское дно / Прибрежный риф', ja:'海底・沿岸の岩礁',
    'pt-BR':'Fundo do Mar / Recife Costeiro', es:'Fondo Marino / Arrecife Costero', ko:'해저/해안 암초',
  },
  '极地/雪原冰川': {
    zh:'极地/雪原冰川', 'zh-TW':'極地/雪原冰川', en:'Polar / Icefield Glacier', de:'Polarregion / Gletscher',
    fr:'Pôle / Glacier', ru:'Полярный край / Ледник', ja:'極地・雪原氷河',
    'pt-BR':'Polar / Geleira', es:'Polar / Glaciar', ko:'극지/설원 빙하',
  },
  '火山/熔岩区': {
    zh:'火山/熔岩区', 'zh-TW':'火山/熔岩區', en:'Volcano / Lava Zone', de:'Vulkan / Lavazone',
    fr:'Volcan / Zone de lave', ru:'Вулкан / Лавовая зона', ja:'火山・溶岩地帯',
    'pt-BR':'Vulcão / Zona de Lava', es:'Volcán / Zona de Lava', ko:'화산/용암 지대',
  },
  '深层洞穴/矿脉核心': {
    zh:'深层洞穴/矿脉核心', 'zh-TW':'深層洞穴/礦脈核心', en:'Deep Cave / Vein Core', de:'Tiefe Höhle / Adernkern',
    fr:'Grotte profonde / Cœur du filon', ru:'Глубокая пещера / Ядро жилы', ja:'深層洞窟・鉱脈の核心',
    'pt-BR':'Caverna Profunda / Núcleo do Veio', es:'Cueva Profunda / Núcleo del Filón', ko:'심층 동굴/광맥 핵심',
  },
};

// Display names for all 103 minerals (dex, warehouse, tooltips, catch toasts,
// haul results). Keyed by the original Chinese mineral name (MINERALS[i].name),
// which stays the internal id used throughout game logic (MIN_BY_NAME, inventory,
// discovered, caughtLog, etc). Use minName(m) in index.html to read the localized label.
const MINERAL_NAME_I18N = {
  '铁矿石': { zh:'铁矿石', 'zh-TW':'鐵礦石', en:'Iron Ore', de:'Eisenerz', fr:'Minerai de fer', ru:'Железная руда', ja:'鉄鉱石', 'pt-BR':'Minério de Ferro', es:'Mineral de Hierro', ko:'철광석' },
  '铜矿石': { zh:'铜矿石', 'zh-TW':'銅礦石', en:'Copper Ore', de:'Kupfererz', fr:'Minerai de cuivre', ru:'Медная руда', ja:'銅鉱石', 'pt-BR':'Minério de Cobre', es:'Mineral de Cobre', ko:'구리광석' },
  '铝土矿': { zh:'铝土矿', 'zh-TW':'鋁土礦', en:'Bauxite', de:'Bauxit', fr:'Bauxite', ru:'Боксит', ja:'ボーキサイト', 'pt-BR':'Bauxita', es:'Bauxita', ko:'보크사이트' },
  '锡石': { zh:'锡石', 'zh-TW':'錫石', en:'Cassiterite', de:'Zinnstein (Kassiterit)', fr:'Cassitérite', ru:'Касситерит', ja:'錫石', 'pt-BR':'Cassiterita', es:'Casiterita', ko:'주석석' },
  '方铅矿': { zh:'方铅矿', 'zh-TW':'方鉛礦', en:'Galena', de:'Bleiglanz', fr:'Galène', ru:'Галенит', ja:'方鉛鉱', 'pt-BR':'Galena', es:'Galena', ko:'방연석' },
  '闪锌矿': { zh:'闪锌矿', 'zh-TW':'閃鋅礦', en:'Sphalerite', de:'Zinkblende', fr:'Sphalérite', ru:'Сфалерит', ja:'閃亜鉛鉱', 'pt-BR':'Esfalerita', es:'Esfalerita', ko:'섬아연석' },
  '辉钼矿': { zh:'辉钼矿', 'zh-TW':'輝鉬礦', en:'Molybdenite', de:'Molybdänglanz', fr:'Molybdénite', ru:'Молибденит', ja:'輝水鉛鉱', 'pt-BR':'Molibdenita', es:'Molibdenita', ko:'휘수연석' },
  '镍矿': { zh:'镍矿', 'zh-TW':'鎳礦', en:'Nickel Ore', de:'Nickelerz', fr:'Minerai de nickel', ru:'Никелевая руда', ja:'ニッケル鉱', 'pt-BR':'Minério de Níquel', es:'Mineral de Níquel', ko:'니켈광' },
  '钨矿': { zh:'钨矿', 'zh-TW':'鎢礦', en:'Tungsten Ore', de:'Wolframerz', fr:'Minerai de tungstène', ru:'Вольфрамовая руда', ja:'タングステン鉱', 'pt-BR':'Minério de Tungstênio', es:'Mineral de Wolframio', ko:'텅스텐광' },
  '金矿脉': { zh:'金矿脉', 'zh-TW':'金礦脈', en:'Gold Vein', de:'Goldader', fr:'Filon d\'or', ru:'Золотая жила', ja:'金鉱脈', 'pt-BR':'Veio de Ouro', es:'Vena de Oro', ko:'금맥' },
  '银矿脉': { zh:'银矿脉', 'zh-TW':'銀礦脈', en:'Silver Vein', de:'Silberader', fr:'Filon d\'argent', ru:'Серебряная жила', ja:'銀鉱脈', 'pt-BR':'Veio de Prata', es:'Vena de Plata', ko:'은맥' },
  '铬铁矿': { zh:'铬铁矿', 'zh-TW':'鉻鐵礦', en:'Chromite', de:'Chromit', fr:'Chromite', ru:'Хромит', ja:'クロム鉄鉱', 'pt-BR':'Cromita', es:'Cromita', ko:'크롬철석' },
  '锰矿': { zh:'锰矿', 'zh-TW':'錳礦', en:'Manganese Ore', de:'Manganerz', fr:'Minerai de manganèse', ru:'Марганцевая руда', ja:'マンガン鉱', 'pt-BR':'Minério de Manganês', es:'Mineral de Manganeso', ko:'망간광' },
  '煤': { zh:'煤', 'zh-TW':'煤', en:'Coal', de:'Kohle', fr:'Charbon', ru:'Уголь', ja:'石炭', 'pt-BR':'Carvão', es:'Carbón', ko:'석탄' },
  '褐煤': { zh:'褐煤', 'zh-TW':'褐煤', en:'Lignite', de:'Braunkohle', fr:'Lignite', ru:'Бурый уголь', ja:'褐炭', 'pt-BR':'Linhito', es:'Lignito', ko:'갈탄' },
  '石油沥青': { zh:'石油沥青', 'zh-TW':'石油瀝青', en:'Petroleum Bitumen', de:'Erdölbitumen', fr:'Bitume pétrolier', ru:'Нефтяной битум', ja:'石油アスファルト', 'pt-BR':'Betume de Petróleo', es:'Betún de Petróleo', ko:'석유 역청' },
  '油页岩': { zh:'油页岩', 'zh-TW':'油頁岩', en:'Oil Shale', de:'Ölschiefer', fr:'Schiste bitumineux', ru:'Горючий сланец', ja:'オイルシェール', 'pt-BR':'Xisto Betuminoso', es:'Esquisto Bituminoso', ko:'유혈암' },
  '铀矿': { zh:'铀矿', 'zh-TW':'鈾礦', en:'Uranium Ore', de:'Uranerz', fr:'Minerai d\'uranium', ru:'Урановая руда', ja:'ウラン鉱', 'pt-BR':'Minério de Urânio', es:'Mineral de Uranio', ko:'우라늄광' },
  '石灰石': { zh:'石灰石', 'zh-TW':'石灰石', en:'Limestone', de:'Kalkstein', fr:'Calcaire', ru:'Известняк', ja:'石灰岩', 'pt-BR':'Calcário', es:'Piedra Caliza', ko:'석회석' },
  '石膏': { zh:'石膏', 'zh-TW':'石膏', en:'Gypsum', de:'Gips', fr:'Gypse', ru:'Гипс', ja:'石膏', 'pt-BR':'Gesso', es:'Yeso', ko:'석고' },
  '花岗岩': { zh:'花岗岩', 'zh-TW':'花崗岩', en:'Granite', de:'Granit', fr:'Granite', ru:'Гранит', ja:'花崗岩', 'pt-BR':'Granito', es:'Granito', ko:'화강암' },
  '大理岩': { zh:'大理岩', 'zh-TW':'大理岩', en:'Marble', de:'Marmor', fr:'Marbre', ru:'Мрамор', ja:'大理石', 'pt-BR':'Mármore', es:'Mármol', ko:'대리암' },
  '石英砂': { zh:'石英砂', 'zh-TW':'石英砂', en:'Quartz Sand', de:'Quarzsand', fr:'Sable de quartz', ru:'Кварцевый песок', ja:'石英砂', 'pt-BR':'Areia de Quartzo', es:'Arena de Cuarzo', ko:'석영사' },
  '高岭土': { zh:'高岭土', 'zh-TW':'高嶺土', en:'Kaolin', de:'Kaolin', fr:'Kaolin', ru:'Каолин', ja:'カオリン', 'pt-BR':'Caulim', es:'Caolín', ko:'고령토' },
  '萤石': { zh:'萤石', 'zh-TW':'螢石', en:'Fluorite', de:'Flussspat', fr:'Fluorite', ru:'Флюорит', ja:'蛍石', 'pt-BR':'Fluorita', es:'Fluorita', ko:'형석' },
  '重晶石': { zh:'重晶石', 'zh-TW':'重晶石', en:'Barite', de:'Baryt', fr:'Baryte', ru:'Барит', ja:'重晶石', 'pt-BR':'Barita', es:'Barita', ko:'중정석' },
  '磷灰石': { zh:'磷灰石', 'zh-TW':'磷灰石', en:'Apatite', de:'Apatit', fr:'Apatite', ru:'Апатит', ja:'燐灰石', 'pt-BR':'Apatita', es:'Apatito', ko:'인회석' },
  '硫磺': { zh:'硫磺', 'zh-TW':'硫磺', en:'Sulfur', de:'Schwefel', fr:'Soufre', ru:'Сера', ja:'硫黄', 'pt-BR':'Enxofre', es:'Azufre', ko:'유황' },
  '岩盐': { zh:'岩盐', 'zh-TW':'岩鹽', en:'Rock Salt', de:'Steinsalz', fr:'Sel gemme', ru:'Каменная соль', ja:'岩塩', 'pt-BR':'Sal-gema', es:'Sal Gema', ko:'암염' },
  '石棉': { zh:'石棉', 'zh-TW':'石棉', en:'Asbestos', de:'Asbest', fr:'Amiante', ru:'Асбест', ja:'石綿', 'pt-BR':'Amianto', es:'Asbesto', ko:'석면' },
  '云母': { zh:'云母', 'zh-TW':'雲母', en:'Mica', de:'Glimmer', fr:'Mica', ru:'Слюда', ja:'雲母', 'pt-BR':'Mica', es:'Mica', ko:'운모' },
  '滑石': { zh:'滑石', 'zh-TW':'滑石', en:'Talc', de:'Talk', fr:'Talc', ru:'Тальк', ja:'滑石', 'pt-BR':'Talco', es:'Talco', ko:'활석' },
  '硼砂': { zh:'硼砂', 'zh-TW':'硼砂', en:'Borax', de:'Borax', fr:'Borax', ru:'Бура', ja:'ホウ砂', 'pt-BR':'Bórax', es:'Bórax', ko:'붕사' },
  '黑曜岩': { zh:'黑曜岩', 'zh-TW':'黑曜岩', en:'Obsidian', de:'Obsidian', fr:'Obsidienne', ru:'Обсидиан', ja:'黒曜石', 'pt-BR':'Obsidiana', es:'Obsidiana', ko:'흑요석' },
  '泥煤': { zh:'泥煤', 'zh-TW':'泥煤', en:'Peat', de:'Torf', fr:'Tourbe', ru:'Торф', ja:'泥炭', 'pt-BR':'Turfa', es:'Turba', ko:'이탄' },
  '褐铁矿': { zh:'褐铁矿', 'zh-TW':'褐鐵礦', en:'Limonite', de:'Limonit', fr:'Limonite', ru:'Лимонит', ja:'褐鉄鉱', 'pt-BR':'Limonita', es:'Limonita', ko:'갈철석' },
  '冰': { zh:'冰', 'zh-TW':'冰', en:'Ice', de:'Eis', fr:'Glace', ru:'Лёд', ja:'氷', 'pt-BR':'Gelo', es:'Hielo', ko:'얼음' },
  '火山岩': { zh:'火山岩', 'zh-TW':'火山岩', en:'Volcanic Rock', de:'Vulkangestein', fr:'Roche volcanique', ru:'Вулканическая порода', ja:'火山岩', 'pt-BR':'Rocha Vulcânica', es:'Roca Volcánica', ko:'화산암' },
  '脉石': { zh:'脉石', 'zh-TW':'脈石', en:'Gangue', de:'Gangart', fr:'Gangue', ru:'Пустая порода', ja:'脈石', 'pt-BR':'Ganga', es:'Ganga', ko:'맥석' },
  '钻石': { zh:'钻石', 'zh-TW':'鑽石', en:'Diamond', de:'Diamant', fr:'Diamant', ru:'Алмаз', ja:'ダイヤモンド', 'pt-BR':'Diamante', es:'Diamante', ko:'다이아몬드' },
  '红宝石': { zh:'红宝石', 'zh-TW':'紅寶石', en:'Ruby', de:'Rubin', fr:'Rubis', ru:'Рубин', ja:'ルビー', 'pt-BR':'Rubi', es:'Rubí', ko:'루비' },
  '蓝宝石': { zh:'蓝宝石', 'zh-TW':'藍寶石', en:'Sapphire', de:'Saphir', fr:'Saphir', ru:'Сапфир', ja:'サファイア', 'pt-BR':'Safira', es:'Zafiro', ko:'사파이어' },
  '祖母绿': { zh:'祖母绿', 'zh-TW':'祖母綠', en:'Emerald', de:'Smaragd', fr:'Émeraude', ru:'Изумруд', ja:'エメラルド', 'pt-BR':'Esmeralda', es:'Esmeralda', ko:'에메랄드' },
  '金绿宝石': { zh:'金绿宝石', 'zh-TW':'金綠寶石', en:'Chrysoberyl', de:'Chrysoberyll', fr:'Chrysobéryl', ru:'Хризоберилл', ja:'クリソベリル', 'pt-BR':'Crisoberilo', es:'Crisoberilo', ko:'금록석' },
  '碧玺': { zh:'碧玺', 'zh-TW':'碧璽', en:'Tourmaline', de:'Turmalin', fr:'Tourmaline', ru:'Турмалин', ja:'トルマリン', 'pt-BR':'Turmalina', es:'Turmalina', ko:'전기석' },
  '坦桑石': { zh:'坦桑石', 'zh-TW':'丹泉石', en:'Tanzanite', de:'Tansanit', fr:'Tanzanite', ru:'Танзанит', ja:'タンザナイト', 'pt-BR':'Tanzanita', es:'Tanzanita', ko:'탄자나이트' },
  '尖晶石': { zh:'尖晶石', 'zh-TW':'尖晶石', en:'Spinel', de:'Spinell', fr:'Spinelle', ru:'Шпинель', ja:'スピネル', 'pt-BR':'Espinélio', es:'Espinela', ko:'첨정석' },
  '石榴石': { zh:'石榴石', 'zh-TW':'石榴石', en:'Garnet', de:'Granat', fr:'Grenat', ru:'Гранат', ja:'ガーネット', 'pt-BR':'Granada', es:'Granate', ko:'석류석' },
  '托帕石': { zh:'托帕石', 'zh-TW':'托帕石', en:'Topaz', de:'Topas', fr:'Topaze', ru:'Топаз', ja:'トパーズ', 'pt-BR':'Topázio', es:'Topacio', ko:'토파즈' },
  '橄榄石': { zh:'橄榄石', 'zh-TW':'橄欖石', en:'Peridot', de:'Peridot', fr:'Péridot', ru:'Перидот', ja:'ペリドット', 'pt-BR':'Peridoto', es:'Peridoto', ko:'감람석' },
  '海蓝宝石': { zh:'海蓝宝石', 'zh-TW':'海藍寶石', en:'Aquamarine', de:'Aquamarin', fr:'Aigue-marine', ru:'Аквамарин', ja:'アクアマリン', 'pt-BR':'Água-marinha', es:'Aguamarina', ko:'아쿠아마린' },
  '摩根石': { zh:'摩根石', 'zh-TW':'摩根石', en:'Morganite', de:'Morganit', fr:'Morganite', ru:'Морганит', ja:'モルガナイト', 'pt-BR':'Morganita', es:'Morganita', ko:'모간석' },
  '月光石': { zh:'月光石', 'zh-TW':'月光石', en:'Moonstone', de:'Mondstein', fr:'Pierre de lune', ru:'Лунный камень', ja:'ムーンストーン', 'pt-BR':'Pedra da Lua', es:'Piedra Lunar', ko:'월장석' },
  '拉长石': { zh:'拉长石', 'zh-TW':'拉長石', en:'Labradorite', de:'Labradorit', fr:'Labradorite', ru:'Лабрадорит', ja:'ラブラドライト', 'pt-BR':'Labradorita', es:'Labradorita', ko:'래브라도라이트' },
  '紫水晶': { zh:'紫水晶', 'zh-TW':'紫水晶', en:'Amethyst', de:'Amethyst', fr:'Améthyste', ru:'Аметист', ja:'アメジスト', 'pt-BR':'Ametista', es:'Amatista', ko:'자수정' },
  '烟晶': { zh:'烟晶', 'zh-TW':'煙晶', en:'Smoky Quartz', de:'Rauchquarz', fr:'Quartz fumé', ru:'Дымчатый кварц', ja:'煙水晶', 'pt-BR':'Quartzo Fumê', es:'Cuarzo Ahumado', ko:'연수정' },
  '白水晶': { zh:'白水晶', 'zh-TW':'白水晶', en:'Clear Quartz', de:'Bergkristall', fr:'Cristal de roche', ru:'Горный хрусталь', ja:'水晶', 'pt-BR':'Cristal de Rocha', es:'Cuarzo Transparente', ko:'백수정' },
  '黄水晶': { zh:'黄水晶', 'zh-TW':'黃水晶', en:'Citrine', de:'Citrin', fr:'Citrine', ru:'Цитрин', ja:'シトリン', 'pt-BR':'Citrino', es:'Citrino', ko:'황수정' },
  '玫瑰石英': { zh:'玫瑰石英', 'zh-TW':'玫瑰石英', en:'Rose Quartz', de:'Rosenquarz', fr:'Quartz rose', ru:'Розовый кварц', ja:'ローズクォーツ', 'pt-BR':'Quartzo Rosa', es:'Cuarzo Rosa', ko:'장미석영' },
  '方解石晶体': { zh:'方解石晶体', 'zh-TW':'方解石晶體', en:'Calcite Crystal', de:'Kalzitkristall', fr:'Cristal de calcite', ru:'Кристалл кальцита', ja:'方解石結晶', 'pt-BR':'Cristal de Calcita', es:'Cristal de Calcita', ko:'방해석 결정' },
  '天青石': { zh:'天青石', 'zh-TW':'天青石', en:'Celestite', de:'Cölestin', fr:'Célestine', ru:'Целестин', ja:'天青石', 'pt-BR':'Celestita', es:'Celestina', ko:'천청석' },
  '蛋白石': { zh:'蛋白石', 'zh-TW':'蛋白石', en:'Opal', de:'Opal', fr:'Opale', ru:'Опал', ja:'オパール', 'pt-BR':'Opala', es:'Ópalo', ko:'오팔' },
  '翡翠': { zh:'翡翠', 'zh-TW':'翡翠', en:'Jadeite', de:'Jadeit', fr:'Jadéite', ru:'Жадеит', ja:'翡翠（ひすい）', 'pt-BR':'Jadeíta', es:'Jadeíta', ko:'비취(경옥)' },
  '和田玉': { zh:'和田玉', 'zh-TW':'和田玉', en:'Hetian Jade (Nephrite)', de:'Hetian-Jade (Nephrit)', fr:'Jade de Hetian (néphrite)', ru:'Хотанский нефрит', ja:'和田玉（ネフライト）', 'pt-BR':'Jade de Hetian (Nefrita)', es:'Jade de Hetian (Nefrita)', ko:'화전옥(연옥)' },
  '青金石': { zh:'青金石', 'zh-TW':'青金石', en:'Lapis Lazuli', de:'Lapislazuli', fr:'Lapis-lazuli', ru:'Лазурит', ja:'ラピスラズリ', 'pt-BR':'Lápis-lazúli', es:'Lapislázuli', ko:'청금석' },
  '绿松石': { zh:'绿松石', 'zh-TW':'綠松石', en:'Turquoise', de:'Türkis', fr:'Turquoise', ru:'Бирюза', ja:'トルコ石', 'pt-BR':'Turquesa', es:'Turquesa', ko:'터키석' },
  '玛瑙': { zh:'玛瑙', 'zh-TW':'瑪瑙', en:'Agate', de:'Achat', fr:'Agate', ru:'Агат', ja:'瑪瑙', 'pt-BR':'Ágata', es:'Ágata', ko:'마노' },
  '孔雀石': { zh:'孔雀石', 'zh-TW':'孔雀石', en:'Malachite', de:'Malachit', fr:'Malachite', ru:'Малахит', ja:'孔雀石', 'pt-BR':'Malaquita', es:'Malaquita', ko:'공작석' },
  '虎眼石': { zh:'虎眼石', 'zh-TW':'虎眼石', en:'Tiger\'s Eye', de:'Tigerauge', fr:'Œil-de-tigre', ru:'Тигровый глаз', ja:'タイガーアイ', 'pt-BR':'Olho-de-Tigre', es:'Ojo de Tigre', ko:'호안석' },
  '珍珠': { zh:'珍珠', 'zh-TW':'珍珠', en:'Pearl', de:'Perle', fr:'Perle', ru:'Жемчуг', ja:'真珠', 'pt-BR':'Pérola', es:'Perla', ko:'진주' },
  '冰洲石': { zh:'冰洲石', 'zh-TW':'冰洲石', en:'Iceland Spar', de:'Doppelspat (Islandspat)', fr:'Spath d\'Islande', ru:'Исландский шпат', ja:'アイスランドスパー', 'pt-BR':'Espato da Islândia', es:'Espato de Islandia', ko:'아이슬란드 방해석' },
  '三叶虫化石': { zh:'三叶虫化石', 'zh-TW':'三葉蟲化石', en:'Trilobite Fossil', de:'Trilobiten-Fossil', fr:'Fossile de trilobite', ru:'Окаменелость трилобита', ja:'三葉虫化石', 'pt-BR':'Fóssil de Trilobita', es:'Fósil de Trilobites', ko:'삼엽충 화석' },
  '菊石化石': { zh:'菊石化石', 'zh-TW':'菊石化石', en:'Ammonite Fossil', de:'Ammoniten-Fossil', fr:'Fossile d\'ammonite', ru:'Окаменелость аммонита', ja:'アンモナイト化石', 'pt-BR':'Fóssil de Amonite', es:'Fósil de Amonita', ko:'암모나이트 화석' },
  '恐龙牙齿化石': { zh:'恐龙牙齿化石', 'zh-TW':'恐龍牙齒化石', en:'Dinosaur Tooth Fossil', de:'Dinosaurierzahn-Fossil', fr:'Fossile de dent de dinosaure', ru:'Окаменелый зуб динозавра', ja:'恐竜の歯化石', 'pt-BR':'Fóssil de Dente de Dinossauro', es:'Fósil de Diente de Dinosaurio', ko:'공룡 이빨 화석' },
  '恐龙蛋化石': { zh:'恐龙蛋化石', 'zh-TW':'恐龍蛋化石', en:'Dinosaur Egg Fossil', de:'Dinosaurierei-Fossil', fr:'Fossile d\'œuf de dinosaure', ru:'Окаменелое яйцо динозавра', ja:'恐竜卵化石', 'pt-BR':'Fóssil de Ovo de Dinossauro', es:'Fósil de Huevo de Dinosaurio', ko:'공룡알 화석' },
  '猛犸象牙化石': { zh:'猛犸象牙化石', 'zh-TW':'猛獁象牙化石', en:'Mammoth Ivory Fossil', de:'Mammutelfenbein-Fossil', fr:'Fossile d\'ivoire de mammouth', ru:'Ископаемый мамонтовый бивень', ja:'マンモスの牙化石', 'pt-BR':'Fóssil de Marfim de Mamute', es:'Fósil de Marfil de Mamut', ko:'매머드 상아 화석' },
  '琥珀(含虫)': { zh:'琥珀(含虫)', 'zh-TW':'琥珀(含蟲)', en:'Amber (with insect)', de:'Bernstein (mit Insekt)', fr:'Ambre (avec insecte)', ru:'Янтарь (с насекомым)', ja:'琥珀（虫入り）', 'pt-BR':'Âmbar (com inseto)', es:'Ámbar (con insecto)', ko:'호박(곤충 포함)' },
  '鱼化石': { zh:'鱼化石', 'zh-TW':'魚化石', en:'Fish Fossil', de:'Fischfossil', fr:'Fossile de poisson', ru:'Окаменелость рыбы', ja:'魚類化石', 'pt-BR':'Fóssil de Peixe', es:'Fósil de Pez', ko:'어류 화석' },
  '蕨类植物化石': { zh:'蕨类植物化石', 'zh-TW':'蕨類植物化石', en:'Fern Fossil', de:'Farnfossil', fr:'Fossile de fougère', ru:'Окаменелость папоротника', ja:'シダ植物化石', 'pt-BR':'Fóssil de Samambaia', es:'Fósil de Helecho', ko:'양치식물 화석' },
  '贝壳化石': { zh:'贝壳化石', 'zh-TW':'貝殼化石', en:'Shell Fossil', de:'Muschelfossil', fr:'Fossile de coquillage', ru:'Окаменелая раковина', ja:'貝殻化石', 'pt-BR':'Fóssil de Concha', es:'Fósil de Concha', ko:'조개껍데기 화석' },
  '始祖鸟化石': { zh:'始祖鸟化石', 'zh-TW':'始祖鳥化石', en:'Archaeopteryx Fossil', de:'Archaeopteryx-Fossil', fr:'Fossile d\'archéoptéryx', ru:'Окаменелость археоптерикса', ja:'始祖鳥化石', 'pt-BR':'Fóssil de Archaeopteryx', es:'Fósil de Arqueópterix', ko:'시조새 화석' },
  '三角龙头骨化石': { zh:'三角龙头骨化石', 'zh-TW':'三角龍頭骨化石', en:'Triceratops Skull Fossil', de:'Triceratops-Schädelfossil', fr:'Fossile de crâne de tricératops', ru:'Окаменелый череп трицератопса', ja:'トリケラトプス頭骨化石', 'pt-BR':'Fóssil de Crânio de Triceratops', es:'Fósil de Cráneo de Triceratops', ko:'트리케라톱스 두개골 화석' },
  '珊瑚化石': { zh:'珊瑚化石', 'zh-TW':'珊瑚化石', en:'Coral Fossil', de:'Korallenfossil', fr:'Fossile de corail', ru:'Окаменелый коралл', ja:'サンゴ化石', 'pt-BR':'Fóssil de Coral', es:'Fósil de Coral', ko:'산호 화석' },
  '硅化木': { zh:'硅化木', 'zh-TW':'矽化木', en:'Petrified Wood', de:'Versteinertes Holz', fr:'Bois pétrifié', ru:'Окаменелое дерево', ja:'珪化木', 'pt-BR':'Madeira Petrificada', es:'Madera Petrificada', ko:'규화목' },
  '磷叶石': { zh:'磷叶石', 'zh-TW':'磷葉石', en:'Phosphophyllite', de:'Phosphophyllit', fr:'Phosphophyllite', ru:'Фосфофиллит', ja:'燐葉石（フォスフォフィライト）', 'pt-BR':'Fosfofilita', es:'Fosfofilita', ko:'인엽석' },
  '辰砂': { zh:'辰砂', 'zh-TW':'辰砂', en:'Cinnabar', de:'Zinnober', fr:'Cinabre', ru:'Киноварь', ja:'辰砂', 'pt-BR':'Cinábrio', es:'Cinabrio', ko:'진사' },
  '圆粒金刚石(波札)': { zh:'圆粒金刚石(波札)', 'zh-TW':'圓粒金剛石(波札)', en:'Boart Diamond', de:'Bort-Diamant', fr:'Diamant bort', ru:'Борт (алмаз)', ja:'バラス（丸粒ダイヤモンド）', 'pt-BR':'Diamante Bort', es:'Diamante Bort', ko:'보르츠 다이아몬드' },
  '黄钻': { zh:'黄钻', 'zh-TW':'黃鑽', en:'Yellow Diamond', de:'Gelber Diamant', fr:'Diamant jaune', ru:'Жёлтый алмаз', ja:'イエローダイヤモンド', 'pt-BR':'Diamante Amarelo', es:'Diamante Amarillo', ko:'옐로 다이아몬드' },
  '红钻石': { zh:'红钻石', 'zh-TW':'紅鑽石', en:'Red Diamond', de:'Roter Diamant', fr:'Diamant rouge', ru:'Красный алмаз', ja:'レッドダイヤモンド', 'pt-BR':'Diamante Vermelho', es:'Diamante Rojo', ko:'레드 다이아몬드' },
  '金红石': { zh:'金红石', 'zh-TW':'金紅石', en:'Rutile', de:'Rutil', fr:'Rutile', ru:'Рутил', ja:'金紅石（ルチル）', 'pt-BR':'Rutilo', es:'Rutilo', ko:'금홍석' },
  '变石(亚历山大变石)': { zh:'变石(亚历山大变石)', 'zh-TW':'變石(亞歷山大變石)', en:'Alexandrite', de:'Alexandrit', fr:'Alexandrite', ru:'Александрит', ja:'アレキサンドライト', 'pt-BR':'Alexandrita', es:'Alejandrita', ko:'알렉산드라이트' },
  '蓝锥矿': { zh:'蓝锥矿', 'zh-TW':'藍錐礦', en:'Benitoite', de:'Benitoit', fr:'Bénitoïte', ru:'Бенитоит', ja:'ベニトアイト', 'pt-BR':'Benitoíta', es:'Benitoíta', ko:'벤이토석' },
  '帕德玛刚玉': { zh:'帕德玛刚玉', 'zh-TW':'帕德瑪剛玉', en:'Padparadscha Sapphire', de:'Padparadscha-Saphir', fr:'Saphir padparadscha', ru:'Сапфир падпараджа', ja:'パパラチアサファイア', 'pt-BR':'Safira Padparadscha', es:'Zafiro Padparadscha', ko:'파파라차 사파이어' },
  '透绿柱石': { zh:'透绿柱石', 'zh-TW':'透綠柱石', en:'Goshenite', de:'Goshenit', fr:'Goshénite', ru:'Гошенит', ja:'ゴシェナイト', 'pt-BR':'Goshenita', es:'Goshenita', ko:'고셰나이트' },
  '红绿柱石': { zh:'红绿柱石', 'zh-TW':'紅綠柱石', en:'Red Beryl', de:'Roter Beryll (Bixbit)', fr:'Béryl rouge', ru:'Красный берилл', ja:'レッドベリル', 'pt-BR':'Berilo Vermelho', es:'Berilo Rojo', ko:'레드베릴' },
  '金绿柱石': { zh:'金绿柱石', 'zh-TW':'金綠柱石', en:'Golden Beryl', de:'Goldberyll (Heliodor)', fr:'Béryl doré (héliodore)', ru:'Гелиодор', ja:'ヘリオドール', 'pt-BR':'Berilo Dourado', es:'Berilo Dorado', ko:'헬리오도르' },
  '南极石': { zh:'南极石', 'zh-TW':'南極石', en:'Antarcticite', de:'Antarktikit', fr:'Antarcticite', ru:'Антарктикит', ja:'南極石', 'pt-BR':'Antarcticita', es:'Antarcticita', ko:'남극석' },
  '异极矿': { zh:'异极矿', 'zh-TW':'異極礦', en:'Hemimorphite', de:'Hemimorphit', fr:'Hémimorphite', ru:'Гемиморфит', ja:'異極鉱', 'pt-BR':'Hemimorfita', es:'Hemimorfita', ko:'이극석' },
  '蓝柱石': { zh:'蓝柱石', 'zh-TW':'藍柱石', en:'Euclase', de:'Euklas', fr:'Euclase', ru:'Эвклаз', ja:'藍柱石（ユークレース）', 'pt-BR':'Euclásio', es:'Euclasa', ko:'남주석' },
  '幽灵水晶': { zh:'幽灵水晶', 'zh-TW':'幽靈水晶', en:'Phantom Quartz', de:'Phantomquarz', fr:'Quartz fantôme', ru:'Фантомный кварц', ja:'ファントムクォーツ', 'pt-BR':'Quartzo Fantasma', es:'Cuarzo Fantasma', ko:'팬텀 수정' },
  '黑水晶(墨晶)': { zh:'黑水晶(墨晶)', 'zh-TW':'黑水晶(墨晶)', en:'Black Quartz (Morion)', de:'Morion (Schwarzquarz)', fr:'Quartz noir (morion)', ru:'Морион', ja:'黒水晶（モリオン）', 'pt-BR':'Quartzo Negro (Morion)', es:'Cuarzo Negro (Morión)', ko:'흑수정(묵정)' },
};

// Localized 备注/note text for the 52 minerals that have one (dex tooltip).
// Keyed by the original Chinese mineral name, same key as MINERAL_NAME_I18N.
// Chemical formulas are left as-is (language neutral).
// Use minNote(m) in index.html to read the localized note.
const MINERAL_NOTE_I18N = {
  '铁矿石': { zh:'常见铁矿主要为赤铁矿或磁铁矿，也有菱铁矿FeCO₃', 'zh-TW':'常見鐵礦主要為赤鐵礦或磁鐵礦，也有菱鐵礦FeCO₃', en:'Common iron ore is mainly hematite or magnetite; siderite (FeCO₃) also occurs.', de:'Häufiges Eisenerz ist meist Hämatit oder Magnetit; auch Siderit (FeCO₃) kommt vor.', fr:'Le minerai de fer courant est surtout de l\'hématite ou de la magnétite ; on trouve aussi de la sidérite (FeCO₃).', ru:'Обычная железная руда — это в основном гематит или магнетит; также встречается сидерит (FeCO₃).', ja:'一般的な鉄鉱石は主に赤鉄鉱または磁鉄鉱で、菱鉄鉱（FeCO₃）も見られる。', 'pt-BR':'O minério de ferro comum é principalmente hematita ou magnetita; também ocorre siderita (FeCO₃).', es:'El mineral de hierro común es principalmente hematita o magnetita; también existe la siderita (FeCO₃).', ko:'일반적인 철광석은 주로 적철석 또는 자철석이며, 능철석(FeCO₃)도 있다.' },
  '铜矿石': { zh:'工业铜矿最主要来源，也有辉铜矿Cu₂S、孔雀石等氧化矿', 'zh-TW':'工業銅礦最主要來源，也有輝銅礦Cu₂S、孔雀石等氧化礦', en:'The main industrial source of copper; chalcocite (Cu₂S), malachite and other oxidized ores also occur.', de:'Die wichtigste industrielle Kupferquelle; auch Chalkosin (Cu₂S), Malachit und andere Oxidationserze kommen vor.', fr:'Principale source industrielle de cuivre ; on trouve aussi la chalcosine (Cu₂S), la malachite et d\'autres minerais oxydés.', ru:'Основной промышленный источник меди; также встречаются халькозин (Cu₂S), малахит и другие окисленные руды.', ja:'工業銅鉱の最も主要な供給源で、輝銅鉱（Cu₂S）や孔雀石などの酸化鉱もある。', 'pt-BR':'Principal fonte industrial de cobre; também ocorrem calcosita (Cu₂S), malaquita e outros minérios oxidados.', es:'La principal fuente industrial de cobre; también existen la calcosina (Cu₂S), la malaquita y otros minerales oxidados.', ko:'공업용 구리 광석의 가장 주요한 공급원이며, 휘동석(Cu₂S)이나 공작석 등의 산화광도 있다.' },
  '铝土矿': { zh:'三水铝石+一水软铝石+氧化铁杂质的混合矿石', 'zh-TW':'三水鋁石+一水軟鋁石+氧化鐵雜質的混合礦石', en:'A mixed ore of gibbsite, boehmite and iron oxide impurities.', de:'Ein Mischerz aus Gibbsit, Böhmit und Eisenoxid-Verunreinigungen.', fr:'Un minerai mixte de gibbsite, de boehmite et d\'impuretés d\'oxyde de fer.', ru:'Смешанная руда из гиббсита, бёмита и примесей оксида железа.', ja:'ギブサイト、ベーマイトと酸化鉄不純物からなる混合鉱石。', 'pt-BR':'Um minério misto de gibbsita, boemita e impurezas de óxido de ferro.', es:'Un mineral mixto de gibbsita, boehmita e impurezas de óxido de hierro.', ko:'깁사이트, 뵈마이트와 산화철 불순물이 섞인 혼합 광석.' },
  '镍矿': { zh:'硫化镍矿为主，也有硅酸镍型红土镍矿', 'zh-TW':'硫化鎳礦為主，也有矽酸鎳型紅土鎳礦', en:'Mainly sulfide nickel ore; silicate-type laterite nickel ore also occurs.', de:'Hauptsächlich sulfidisches Nickelerz; auch silikatisches lateritisches Nickelerz kommt vor.', fr:'Principalement du minerai de nickel sulfuré ; on trouve aussi du minerai de nickel latéritique de type silicaté.', ru:'В основном сульфидная никелевая руда; также встречается силикатная латеритная никелевая руда.', ja:'主に硫化ニッケル鉱で、ケイ酸塩型のラテライトニッケル鉱もある。', 'pt-BR':'Principalmente minério de níquel sulfetado; também ocorre minério laterítico de níquel do tipo silicatado.', es:'Principalmente mineral de níquel sulfurado; también existe el mineral laterítico de níquel de tipo silicatado.', ko:'주로 황화 니켈광이며, 규산염형 라테라이트 니켈광도 있다.' },
  '金矿脉': { zh:'多以自然金颗粒赋存于石英脉中', 'zh-TW':'多以自然金顆粒賦存於石英脈中', en:'Mostly native gold grains hosted within quartz veins.', de:'Meist als gediegene Goldkörner in Quarzadern eingelagert.', fr:'Souvent des grains d\'or natif contenus dans des veines de quartz.', ru:'Чаще всего самородные золотые зёрна залегают в кварцевых жилах.', ja:'多くは自然金の粒として石英脈中に含まれる。', 'pt-BR':'Geralmente na forma de grãos de ouro nativo hospedados em veios de quartzo.', es:'Generalmente en forma de granos de oro nativo alojados en vetas de cuarzo.', ko:'대부분 자연금 알갱이가 석영맥 안에 들어있다.' },
  '锰矿': { zh:'也常见Mn₂O₃(黑锰矿)等', 'zh-TW':'也常見Mn₂O₃(黑錳礦)等', en:'Braunite (Mn₂O₃) and other manganese minerals are also common.', de:'Auch Braunit (Mn₂O₃) und andere Manganminerale kommen häufig vor.', fr:'On trouve aussi couramment la braunite (Mn₂O₃) et d\'autres minéraux de manganèse.', ru:'Также часто встречается браунит (Mn₂O₃) и другие марганцевые минералы.', ja:'Mn₂O₃（黒マンガン鉱）なども一般的に見られる。', 'pt-BR':'Braunita (Mn₂O₃) e outros minerais de manganês também são comuns.', es:'La braunita (Mn₂O₃) y otros minerales de manganeso también son comunes.', ko:'Mn₂O₃(흑망간석) 등도 흔히 볼 수 있다.' },
  '煤': { zh:'非严格意义矿物，主体为碳质', 'zh-TW':'非嚴格意義礦物，主體為碳質', en:'Not a mineral in the strict sense; mainly carbonaceous material.', de:'Kein Mineral im strengen Sinne; besteht hauptsächlich aus kohlenstoffhaltigem Material.', fr:'Ce n\'est pas un minéral au sens strict ; principalement composé de matière carbonée.', ru:'Не является минералом в строгом смысле; в основном состоит из углеродистого вещества.', ja:'厳密には鉱物ではなく、主体は炭質物である。', 'pt-BR':'Não é um mineral em sentido estrito; composto principalmente por matéria carbonácea.', es:'No es un mineral en sentido estricto; compuesto principalmente por materia carbonosa.', ko:'엄밀히 말하면 광물이 아니며, 주성분은 탄질물이다.' },
  '褐煤': { zh:'煤化程度低于煤', 'zh-TW':'煤化程度低於煤', en:'A lower rank of coalification than (bituminous) coal.', de:'Geringerer Inkohlungsgrad als (Stein-)Kohle.', fr:'Degré de houillification inférieur à celui du charbon.', ru:'Степень углефикации ниже, чем у каменного угля.', ja:'石炭化度は石炭より低い。', 'pt-BR':'Grau de carbonificação inferior ao do carvão.', es:'Grado de carbonificación inferior al del carbón.', ko:'석탄화 정도가 석탄보다 낮다.' },
  '铀矿': { zh:'沥青铀矿等统称，主要成分UO₂', 'zh-TW':'瀝青鈾礦等統稱，主要成分UO₂', en:'A general term including pitchblende; mainly composed of UO₂.', de:'Sammelbegriff u.a. für Pechblende; besteht hauptsächlich aus UO₂.', fr:'Terme générique incluant la pechblende ; composé principalement d\'UO₂.', ru:'Общее название, включающее уранинит (урановую смолку); в основном состоит из UO₂.', ja:'瀝青ウラン鉱などの総称で、主成分はUO₂。', 'pt-BR':'Termo geral que inclui a pechblenda; composta principalmente de UO₂.', es:'Término general que incluye la pechblenda; compuesta principalmente de UO₂.', ko:'역청우라늄광 등을 통칭하며, 주성분은 UO₂이다.' },
  '石灰石': { zh:'主要成分CaCO₃', 'zh-TW':'主要成分CaCO₃', en:'Mainly composed of CaCO₃.', de:'Besteht hauptsächlich aus CaCO₃.', fr:'Composé principalement de CaCO₃.', ru:'В основном состоит из CaCO₃.', ja:'主成分はCaCO₃。', 'pt-BR':'Composto principalmente de CaCO₃.', es:'Compuesta principalmente de CaCO₃.', ko:'주성분은 CaCO₃이다.' },
  '花岗岩': { zh:'石英+长石+云母等矿物混合岩石', 'zh-TW':'石英+長石+雲母等礦物混合岩石', en:'A rock composed of quartz, feldspar, mica and other minerals.', de:'Ein Gestein aus Quarz, Feldspat, Glimmer und anderen Mineralen.', fr:'Une roche composée de quartz, de feldspath, de mica et d\'autres minéraux.', ru:'Порода, состоящая из кварца, полевого шпата, слюды и других минералов.', ja:'石英・長石・雲母などの鉱物からなる混合岩。', 'pt-BR':'Uma rocha composta por quartzo, feldspato, mica e outros minerais.', es:'Una roca compuesta de cuarzo, feldespato, mica y otros minerales.', ko:'석영, 장석, 운모 등이 섞인 혼합암.' },
  '大理岩': { zh:'变质石灰岩，主要成分CaCO₃', 'zh-TW':'變質石灰岩，主要成分CaCO₃', en:'Metamorphosed limestone; mainly composed of CaCO₃.', de:'Metamorpher Kalkstein; besteht hauptsächlich aus CaCO₃.', fr:'Calcaire métamorphisé ; composé principalement de CaCO₃.', ru:'Метаморфизованный известняк; в основном состоит из CaCO₃.', ja:'変成した石灰岩で、主成分はCaCO₃。', 'pt-BR':'Calcário metamorfizado; composto principalmente de CaCO₃.', es:'Piedra caliza metamorfizada; compuesta principalmente de CaCO₃.', ko:'변성된 석회암으로, 주성분은 CaCO₃이다.' },
  '石棉': { zh:'也有青石棉等角闪石族品种', 'zh-TW':'也有青石棉等角閃石族品種', en:'Crocidolite and other amphibole-group varieties also occur.', de:'Auch Krokydolith und andere Amphibol-Varietäten kommen vor.', fr:'On trouve aussi la crocidolite et d\'autres variétés du groupe des amphiboles.', ru:'Также встречаются крокидолит и другие разновидности группы амфиболов.', ja:'青石綿（クロシドライト）など角閃石族の品種もある。', 'pt-BR':'Crocidolita e outras variedades do grupo dos anfibólios também ocorrem.', es:'La crocidolita y otras variedades del grupo de los anfíboles también existen.', ko:'청석면 등 각섬석족 종류도 있다.' },
  '云母': { zh:'云母族矿物统称', 'zh-TW':'雲母族礦物統稱', en:'A general term for the mica group of minerals.', de:'Ein Sammelbegriff für die Glimmergruppe der Minerale.', fr:'Terme générique pour le groupe minéral des micas.', ru:'Общее название группы слюдяных минералов.', ja:'雲母族鉱物の総称。', 'pt-BR':'Termo geral para o grupo mineral das micas.', es:'Término general para el grupo mineral de las micas.', ko:'운모족 광물의 총칭.' },
  '黑曜岩': { zh:'火山玻璃', 'zh-TW':'火山玻璃', en:'Volcanic glass.', de:'Vulkanisches Glas.', fr:'Verre volcanique.', ru:'Вулканическое стекло.', ja:'火山ガラス。', 'pt-BR':'Vidro vulcânico.', es:'Vidrio volcánico.', ko:'화산 유리.' },
  '火山岩': { zh:'多孔玄武质火山岩', 'zh-TW':'多孔玄武質火山岩', en:'Porous basaltic volcanic rock.', de:'Poröses basaltisches Vulkangestein.', fr:'Roche volcanique basaltique poreuse.', ru:'Пористая базальтовая вулканическая порода.', ja:'多孔質な玄武岩質の火山岩。', 'pt-BR':'Rocha vulcânica basáltica porosa.', es:'Roca volcánica basáltica porosa.', ko:'다공질 현무암질 화산암.' },
  '脉石': { zh:'矿脉里包裹矿石的无价值围岩', 'zh-TW':'礦脈裡包裹礦石的無價值圍岩', en:'The worthless host rock surrounding ore within a vein.', de:'Das wertlose Nebengestein, das das Erz in einer Ader umschließt.', fr:'La roche encaissante sans valeur qui entoure le minerai dans un filon.', ru:'Бесполезная вмещающая порода, окружающая руду в жиле.', ja:'鉱脈の中で鉱石を包む無価値な母岩。', 'pt-BR':'A rocha hospedeira sem valor que envolve o minério em um veio.', es:'La roca encajante sin valor que rodea el mineral en una veta.', ko:'광맥 안에서 광석을 감싸는 가치 없는 모암.' },
  '红宝石': { zh:'刚玉，Cr致色', 'zh-TW':'剛玉，Cr致色', en:'Corundum, colored by chromium.', de:'Korund, durch Chrom gefärbt.', fr:'Corindon, coloré par le chrome.', ru:'Корунд, окрашенный хромом.', ja:'コランダムで、Crによって発色する。', 'pt-BR':'Coríndon, colorido por cromo.', es:'Corindón, coloreado por el cromo.', ko:'강옥(커런덤)이며, 크롬에 의해 색이 난다.' },
  '蓝宝石': { zh:'刚玉，Fe/Ti致色', 'zh-TW':'剛玉，Fe/Ti致色', en:'Corundum, colored by iron and titanium.', de:'Korund, durch Eisen und Titan gefärbt.', fr:'Corindon, coloré par le fer et le titane.', ru:'Корунд, окрашенный железом и титаном.', ja:'コランダムで、Fe/Tiによって発色する。', 'pt-BR':'Coríndon, colorido por ferro e titânio.', es:'Corindón, coloreado por hierro y titanio.', ko:'강옥이며, 철/티타늄에 의해 색이 난다.' },
  '祖母绿': { zh:'绿柱石，Cr致色', 'zh-TW':'綠柱石，Cr致色', en:'Beryl, colored by chromium.', de:'Beryll, durch Chrom gefärbt.', fr:'Béryl, coloré par le chrome.', ru:'Берилл, окрашенный хромом.', ja:'緑柱石で、Crによって発色する。', 'pt-BR':'Berilo, colorido por cromo.', es:'Berilo, coloreado por el cromo.', ko:'녹주석이며, 크롬에 의해 색이 난다.' },
  '碧玺': { zh:'电气石族，成分变化大', 'zh-TW':'電氣石族，成分變化大', en:'A member of the tourmaline group, with highly variable composition.', de:'Gehört zur Turmalingruppe, mit stark variierender Zusammensetzung.', fr:'Membre du groupe des tourmalines, dont la composition varie fortement.', ru:'Представитель группы турмалина с сильно изменчивым составом.', ja:'電気石族に属し、組成の変化が大きい。', 'pt-BR':'Membro do grupo da turmalina, com composição altamente variável.', es:'Miembro del grupo de la turmalina, con composición muy variable.', ko:'전기석족에 속하며 성분 변화가 크다.' },
  '坦桑石': { zh:'黝帘石的蓝色变种', 'zh-TW':'黝簾石的藍色變種', en:'A blue variety of zoisite.', de:'Eine blaue Varietät des Zoisits.', fr:'Une variété bleue de la zoïsite.', ru:'Синяя разновидность цоизита.', ja:'灰簾石（ゾイサイト）の青色変種。', 'pt-BR':'Uma variedade azul da zoisita.', es:'Una variedad azul de la zoisita.', ko:'조이사이트의 청색 변종.' },
  '海蓝宝石': { zh:'绿柱石的蓝色变种', 'zh-TW':'綠柱石的藍色變種', en:'A blue variety of beryl.', de:'Eine blaue Varietät des Berylls.', fr:'Une variété bleue du béryl.', ru:'Синяя разновидность берилла.', ja:'緑柱石の青色変種。', 'pt-BR':'Uma variedade azul do berilo.', es:'Una variedad azul del berilo.', ko:'녹주석의 청색 변종.' },
  '摩根石': { zh:'绿柱石的粉色变种（含锰）', 'zh-TW':'綠柱石的粉色變種（含錳）', en:'A pink variety of beryl (colored by manganese).', de:'Eine rosa Varietät des Berylls (durch Mangan gefärbt).', fr:'Une variété rose du béryl (colorée par le manganèse).', ru:'Розовая разновидность берилла (содержит марганец).', ja:'緑柱石のピンク変種（マンガンを含む）。', 'pt-BR':'Uma variedade rosa do berilo (com manganês).', es:'Una variedad rosa del berilo (con manganeso).', ko:'녹주석의 분홍색 변종(망간 함유).' },
  '月光石': { zh:'钾长石类', 'zh-TW':'鉀長石類', en:'A type of potassium feldspar.', de:'Eine Art Kalifeldspat.', fr:'Un type de feldspath potassique.', ru:'Разновидность калиевого полевого шпата.', ja:'カリ長石の一種。', 'pt-BR':'Um tipo de feldspato potássico.', es:'Un tipo de feldespato potásico.', ko:'칼리장석의 일종.' },
  '拉长石': { zh:'长石族固溶体，只有通式', 'zh-TW':'長石族固溶體，只有通式', en:'A solid solution within the feldspar group; only a general formula exists.', de:'Ein Mischkristall der Feldspatgruppe; es existiert nur eine allgemeine Formel.', fr:'Une solution solide du groupe des feldspaths ; seule une formule générale existe.', ru:'Твёрдый раствор в группе полевых шпатов; существует только общая формула.', ja:'長石族の固溶体で、一般式のみ存在する。', 'pt-BR':'Uma solução sólida do grupo dos feldspatos; existe apenas uma fórmula geral.', es:'Una solución sólida del grupo de los feldespatos; solo existe una fórmula general.', ko:'장석족의 고용체이며, 일반식만 존재한다.' },
  '紫水晶': { zh:'石英', 'zh-TW':'石英', en:'Quartz', de:'Quarz', fr:'Quartz', ru:'Кварц', ja:'石英', 'pt-BR':'Quartzo', es:'Cuarzo', ko:'석영' },
  '烟晶': { zh:'石英', 'zh-TW':'石英', en:'Quartz', de:'Quarz', fr:'Quartz', ru:'Кварц', ja:'石英', 'pt-BR':'Quartzo', es:'Cuarzo', ko:'석영' },
  '白水晶': { zh:'石英', 'zh-TW':'石英', en:'Quartz', de:'Quarz', fr:'Quartz', ru:'Кварц', ja:'石英', 'pt-BR':'Quartzo', es:'Cuarzo', ko:'석영' },
  '黄水晶': { zh:'石英', 'zh-TW':'石英', en:'Quartz', de:'Quarz', fr:'Quartz', ru:'Кварц', ja:'石英', 'pt-BR':'Quartzo', es:'Cuarzo', ko:'석영' },
  '玫瑰石英': { zh:'石英', 'zh-TW':'石英', en:'Quartz', de:'Quarz', fr:'Quartz', ru:'Кварц', ja:'石英', 'pt-BR':'Quartzo', es:'Cuarzo', ko:'석영' },
  '蛋白石': { zh:'非晶质含水二氧化硅', 'zh-TW':'非晶質含水二氧化矽', en:'Amorphous hydrated silica.', de:'Amorphes, wasserhaltiges Siliciumdioxid.', fr:'Silice hydratée amorphe.', ru:'Аморфный гидратированный диоксид кремния.', ja:'非晶質の含水二酸化ケイ素。', 'pt-BR':'Sílica hidratada amorfa.', es:'Sílice hidratada amorfa.', ko:'비정질 함수 이산화규소.' },
  '翡翠': { zh:'硬玉，多产自变质岩带', 'zh-TW':'硬玉，多產自變質岩帶', en:'Jadeite; mostly found in metamorphic rock belts.', de:'Jadeit; meist aus metamorphen Gesteinszonen.', fr:'Jadéite ; provient surtout de zones de roches métamorphiques.', ru:'Жадеит; в основном добывается в поясах метаморфических пород.', ja:'硬玉（ジェダイト）で、変成岩帯から多く産出する。', 'pt-BR':'Jadeíta; encontrada principalmente em cinturões de rochas metamórficas.', es:'Jadeíta; se encuentra principalmente en cinturones de rocas metamórficas.', ko:'경옥이며, 대부분 변성암대에서 산출된다.' },
  '和田玉': { zh:'软玉，透闪石为主', 'zh-TW':'軟玉，透閃石為主', en:'Nephrite jade, mainly tremolite.', de:'Nephrit-Jade, hauptsächlich Tremolit.', fr:'Jade néphrite, principalement composé de trémolite.', ru:'Нефритовый жад, в основном тремолит.', ja:'軟玉で、透閃石を主成分とする。', 'pt-BR':'Jade nefrita, principalmente tremolita.', es:'Jade de nefrita, principalmente tremolita.', ko:'연옥이며, 주로 투섬석으로 이루어진다.' },
  '青金石': { zh:'青金石矿物+方解石+黄铁矿混合', 'zh-TW':'青金石礦物+方解石+黃鐵礦混合', en:'A mix of lazurite, calcite and pyrite.', de:'Eine Mischung aus Lazurit, Calcit und Pyrit.', fr:'Un mélange de lazurite, de calcite et de pyrite.', ru:'Смесь лазурита, кальцита и пирита.', ja:'青金石鉱物・方解石・黄鉄鉱の混合物。', 'pt-BR':'Uma mistura de lazurita, calcita e pirita.', es:'Una mezcla de lazurita, calcita y pirita.', ko:'청금석 광물과 방해석, 황철석이 섞인 것.' },
  '玛瑙': { zh:'隐晶质石英', 'zh-TW':'隱晶質石英', en:'Cryptocrystalline quartz.', de:'Kryptokristalliner Quarz.', fr:'Quartz cryptocristallin.', ru:'Скрытокристаллический кварц.', ja:'隠微晶質の石英。', 'pt-BR':'Quartzo criptocristalino.', es:'Cuarzo criptocristalino.', ko:'은정질 석영.' },
  '孔雀石': { zh:'与铜矿同源', 'zh-TW':'與銅礦同源', en:'Shares the same origin as copper ore.', de:'Hat denselben Ursprung wie Kupfererz.', fr:'A la même origine que le minerai de cuivre.', ru:'Имеет тот же источник, что и медная руда.', ja:'銅鉱と同源である。', 'pt-BR':'Tem a mesma origem do minério de cobre.', es:'Tiene el mismo origen que el mineral de cobre.', ko:'구리 광석과 같은 기원을 가진다.' },
  '虎眼石': { zh:'石英交代青石棉纤维', 'zh-TW':'石英交代青石棉纖維', en:'Quartz that has replaced crocidolite (blue asbestos) fibers.', de:'Quarz, der Krokydolith-(Blauasbest-)Fasern verdrängt hat.', fr:'Quartz ayant remplacé des fibres de crocidolite (amiante bleu).', ru:'Кварц, замещающий волокна крокидолита (голубого асбеста).', ja:'石英が青石綿の繊維を交代したもの。', 'pt-BR':'Quartzo que substituiu fibras de crocidolita (amianto azul).', es:'Cuarzo que ha reemplazado fibras de crocidolita (asbesto azul).', ko:'석영이 청석면 섬유를 교대한 것.' },
  '珍珠': { zh:'文石+有机质的生物矿化复合材料', 'zh-TW':'文石+有機質的生物礦化複合材料', en:'A biomineralized composite of aragonite and organic matter.', de:'Ein biomineralisiertes Verbundmaterial aus Aragonit und organischer Substanz.', fr:'Un matériau composite biominéralisé d\'aragonite et de matière organique.', ru:'Биоминерализованный композит из арагонита и органического вещества.', ja:'アラゴナイトと有機質からなる生体鉱物化複合材料。', 'pt-BR':'Um material composto biomineralizado de aragonita e matéria orgânica.', es:'Un material compuesto biomineralizado de aragonito y materia orgánica.', ko:'아라고나이트와 유기물이 결합된 생체광물 복합재료.' },
  '冰洲石': { zh:'方解石的透明观赏变种，因产自冰岛得名，历史上用于研究光学双折射现象', 'zh-TW':'方解石的透明觀賞變種，因產自冰島得名，歷史上用於研究光學雙折射現象', en:'A transparent, gem-quality variety of calcite named after Iceland, historically used to study optical double refraction.', de:'Eine durchsichtige, dekorative Varietät des Calcits, benannt nach Island, historisch zur Erforschung der optischen Doppelbrechung verwendet.', fr:'Une variété transparente et décorative de la calcite, nommée d\'après l\'Islande, historiquement utilisée pour étudier la double réfraction optique.', ru:'Прозрачная декоративная разновидность кальцита, названная в честь Исландии, исторически использовалась для изучения оптического двойного лучепреломления.', ja:'方解石の透明で観賞用の変種で、アイスランド産にちなんで名付けられ、歴史的に光学的複屈折現象の研究に用いられた。', 'pt-BR':'Uma variedade transparente e ornamental da calcita, nomeada em homenagem à Islândia, historicamente usada para estudar a dupla refração óptica.', es:'Una variedad transparente y ornamental de la calcita, llamada así por Islandia, utilizada históricamente para estudiar la doble refracción óptica.', ko:'방해석의 투명한 관상용 변종으로, 아이슬란드산이라는 이름에서 유래했으며 역사적으로 광학 복굴절 현상 연구에 사용되었다.' },
  '三叶虫化石': { zh:'具体成分取决于石化过程', 'zh-TW':'具體成分取決於石化過程', en:'The exact composition depends on the fossilization process.', de:'Die genaue Zusammensetzung hängt vom Fossilisationsprozess ab.', fr:'La composition exacte dépend du processus de fossilisation.', ru:'Точный состав зависит от процесса окаменения.', ja:'具体的な成分は石化の過程によって異なる。', 'pt-BR':'A composição exata depende do processo de fossilização.', es:'La composición exacta depende del proceso de fosilización.', ko:'구체적인 성분은 화석화 과정에 따라 다르다.' },
  '琥珀(含虫)': { zh:'树脂化石，非严格矿物', 'zh-TW':'樹脂化石，非嚴格礦物', en:'Fossilized resin; not a mineral in the strict sense.', de:'Fossiles Harz; kein Mineral im strengen Sinne.', fr:'Résine fossilisée ; pas un minéral au sens strict.', ru:'Окаменевшая смола; не является минералом в строгом смысле.', ja:'樹脂の化石であり、厳密には鉱物ではない。', 'pt-BR':'Resina fossilizada; não é um mineral em sentido estrito.', es:'Resina fosilizada; no es un mineral en sentido estricto.', ko:'수지가 화석화된 것으로, 엄밀히는 광물이 아니다.' },
  '硅化木': { zh:'木质被二氧化硅交代，主体可视为SiO₂但严格不算矿物', 'zh-TW':'木質被二氧化矽交代，主體可視為SiO₂但嚴格不算礦物', en:'Wood replaced by silica; mainly SiO₂, but not strictly a mineral.', de:'Holz, das durch Kieselsäure ersetzt wurde; hauptsächlich SiO₂, aber im strengen Sinne kein Mineral.', fr:'Bois remplacé par de la silice ; principalement SiO₂, mais pas un minéral au sens strict.', ru:'Древесина, замещённая кремнезёмом; в основном SiO₂, но строго не является минералом.', ja:'木材が二酸化ケイ素に交代したもので、主体はSiO₂とみなせるが厳密には鉱物ではない。', 'pt-BR':'Madeira substituída por sílica; composta principalmente de SiO₂, mas não é um mineral em sentido estrito.', es:'Madera reemplazada por sílice; compuesta principalmente de SiO₂, pero no es un mineral en sentido estricto.', ko:'나무가 이산화규소로 교대된 것으로, 주성분은 SiO₂로 볼 수 있으나 엄밀히는 광물이 아니다.' },
  '黄钻': { zh:'含氮致色的钻石变种', 'zh-TW':'含氮致色的鑽石變種', en:'A diamond variety colored by nitrogen.', de:'Eine Diamantvarietät, die durch Stickstoff gefärbt ist.', fr:'Une variété de diamant colorée par l\'azote.', ru:'Разновидность алмаза, окрашенная азотом.', ja:'窒素を含むことで発色するダイヤモンドの変種。', 'pt-BR':'Uma variedade de diamante colorida por nitrogênio.', es:'Una variedad de diamante coloreada por nitrógeno.', ko:'질소로 인해 색이 나는 다이아몬드 변종.' },
  '红钻石': { zh:'晶格缺陷致色的钻石变种', 'zh-TW':'晶格缺陷致色的鑽石變種', en:'A diamond variety colored by lattice defects.', de:'Eine Diamantvarietät, die durch Gitterdefekte gefärbt ist.', fr:'Une variété de diamant colorée par des défauts du réseau cristallin.', ru:'Разновидность алмаза, окрашенная дефектами кристаллической решётки.', ja:'結晶格子の欠陥によって発色するダイヤモンドの変種。', 'pt-BR':'Uma variedade de diamante colorida por defeitos na estrutura cristalina.', es:'Una variedad de diamante coloreada por defectos en la red cristalina.', ko:'결정격자 결함으로 색이 나는 다이아몬드 변종.' },
  '变石(亚历山大变石)': { zh:'金绿宝石的变色变种', 'zh-TW':'金綠寶石的變色變種', en:'A color-change variety of chrysoberyl.', de:'Eine farbwechselnde Varietät des Chrysoberylls.', fr:'Une variété à changement de couleur du chrysobéryl.', ru:'Разновидность хризоберилла с эффектом смены цвета.', ja:'金緑石（クリソベリル）の変色変種。', 'pt-BR':'Uma variedade de mudança de cor do crisoberilo.', es:'Una variedad de cambio de color del crisoberilo.', ko:'금록석의 변색 변종.' },
  '帕德玛刚玉': { zh:'刚玉的橙粉色变种', 'zh-TW':'剛玉的橙粉色變種', en:'An orange-pink variety of corundum.', de:'Eine orange-rosa Varietät des Korunds.', fr:'Une variété orange-rose du corindon.', ru:'Оранжево-розовая разновидность корунда.', ja:'コランダムの橙ピンク色変種。', 'pt-BR':'Uma variedade laranja-rosada do coríndon.', es:'Una variedad de color naranja rosado del corindón.', ko:'강옥의 주황분홍색 변종.' },
  '透绿柱石': { zh:'绿柱石的无色变种', 'zh-TW':'綠柱石的無色變種', en:'A colorless variety of beryl.', de:'Eine farblose Varietät des Berylls.', fr:'Une variété incolore du béryl.', ru:'Бесцветная разновидность берилла.', ja:'緑柱石の無色変種。', 'pt-BR':'Uma variedade incolor do berilo.', es:'Una variedad incolora del berilo.', ko:'녹주석의 무색 변종.' },
  '红绿柱石': { zh:'绿柱石的红色变种', 'zh-TW':'綠柱石的紅色變種', en:'A red variety of beryl.', de:'Eine rote Varietät des Berylls.', fr:'Une variété rouge du béryl.', ru:'Красная разновидность берилла.', ja:'緑柱石の赤色変種。', 'pt-BR':'Uma variedade vermelha do berilo.', es:'Una variedad roja del berilo.', ko:'녹주석의 붉은색 변종.' },
  '金绿柱石': { zh:'绿柱石的金黄色变种', 'zh-TW':'綠柱石的金黃色變種', en:'A golden-yellow variety of beryl.', de:'Eine goldgelbe Varietät des Berylls.', fr:'Une variété jaune doré du béryl.', ru:'Золотисто-жёлтая разновидность берилла.', ja:'緑柱石の金黄色変種。', 'pt-BR':'Uma variedade dourada-amarela do berilo.', es:'Una variedad amarillo dorado del berilo.', ko:'녹주석의 황금색 변종.' },
  '幽灵水晶': { zh:'幻影水晶，本质仍是石英', 'zh-TW':'幻影水晶，本質仍是石英', en:'Phantom quartz; fundamentally still quartz.', de:'Phantomquarz; im Wesentlichen immer noch Quarz.', fr:'Quartz fantôme ; toujours essentiellement du quartz.', ru:'Фантомный кварц; по сути всё ещё кварц.', ja:'ファントム水晶で、本質は石英である。', 'pt-BR':'Quartzo fantasma; essencialmente ainda é quartzo.', es:'Cuarzo fantasma; en esencia sigue siendo cuarzo.', ko:'팬텀 수정이며, 본질적으로는 석영이다.' },
  '黑水晶(墨晶)': { zh:'烟晶的深色变种', 'zh-TW':'煙晶的深色變種', en:'A dark variety of smoky quartz.', de:'Eine dunkle Varietät des Rauchquarzes.', fr:'Une variété foncée du quartz fumé.', ru:'Тёмная разновидность дымчатого кварца.', ja:'煙水晶の濃色変種。', 'pt-BR':'Uma variedade escura do quartzo fumê.', es:'Una variedad oscura del cuarzo ahumado.', ko:'연수정의 짙은색 변종.' },
};
